// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FMS_ITS_Interface_Specification.proto

package fmsitsinterface;

public interface AnomaliesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fmsitsinterface.Anomalies)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * indicating axle, counting starts from front of vehicle
   * </pre>
   *
   * <code>int32 axle = 1;</code>
   * @return The axle.
   */
  int getAxle();

  /**
   * <pre>
   * indicating side of axle
   * </pre>
   *
   * <code>.fmsitsinterface.Anomalies.Side side = 2;</code>
   * @return The enum numeric value on the wire for side.
   */
  int getSideValue();
  /**
   * <pre>
   * indicating side of axle
   * </pre>
   *
   * <code>.fmsitsinterface.Anomalies.Side side = 2;</code>
   * @return The side.
   */
  fmsitsinterface.Anomalies.Side getSide();

  /**
   * <pre>
   * indicating state of tire
   * </pre>
   *
   * <code>.fmsitsinterface.Anomalies.TireStatus measurement = 3;</code>
   * @return The enum numeric value on the wire for measurement.
   */
  int getMeasurementValue();
  /**
   * <pre>
   * indicating state of tire
   * </pre>
   *
   * <code>.fmsitsinterface.Anomalies.TireStatus measurement = 3;</code>
   * @return The measurement.
   */
  fmsitsinterface.Anomalies.TireStatus getMeasurement();
}
