// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FMS_ITS_Interface_Specification.proto

package fmsitsinterface;

/**
 * Protobuf enum {@code fmsitsinterface.ErrorType}
 */
public enum ErrorType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ERRORTYPE_UNKNOWN = 0;</code>
   */
  ERRORTYPE_UNKNOWN(0),
  /**
   * <pre>
   * an expected field is missing
   * </pre>
   *
   * <code>MISSING_FIELD = 1;</code>
   */
  MISSING_FIELD(1),
  /**
   * <pre>
   * a field has an invalid/unsupported value
   * </pre>
   *
   * <code>INVALID_FIELD = 2;</code>
   */
  INVALID_FIELD(2),
  /**
   * <pre>
   * e.g. the required information via the API was not provided
   * </pre>
   *
   * <code>PRE_CONDITION_NOT_MET = 3;</code>
   */
  PRE_CONDITION_NOT_MET(3),
  /**
   * <pre>
   * locationUpdateEvents are not being received according to specification
   * </pre>
   *
   * <code>DATA_RATE_ERROR = 4;</code>
   */
  DATA_RATE_ERROR(4),
  /**
   * <pre>
   * a timestamp response was not received within the expected timeframe
   * </pre>
   *
   * <code>NO_TIMESTAMP_ANSWER = 5;</code>
   */
  NO_TIMESTAMP_ANSWER(5),
  /**
   * <pre>
   * difference between clocks of FMS and CSP is too big
   * </pre>
   *
   * <code>TIMEDIFF_TOO_BIG = 6;</code>
   */
  TIMEDIFF_TOO_BIG(6),
  /**
   * <pre>
   * proto message could not be decoded
   * </pre>
   *
   * <code>INVALID_PROTO = 7;</code>
   */
  INVALID_PROTO(7),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ERRORTYPE_UNKNOWN = 0;</code>
   */
  public static final int ERRORTYPE_UNKNOWN_VALUE = 0;
  /**
   * <pre>
   * an expected field is missing
   * </pre>
   *
   * <code>MISSING_FIELD = 1;</code>
   */
  public static final int MISSING_FIELD_VALUE = 1;
  /**
   * <pre>
   * a field has an invalid/unsupported value
   * </pre>
   *
   * <code>INVALID_FIELD = 2;</code>
   */
  public static final int INVALID_FIELD_VALUE = 2;
  /**
   * <pre>
   * e.g. the required information via the API was not provided
   * </pre>
   *
   * <code>PRE_CONDITION_NOT_MET = 3;</code>
   */
  public static final int PRE_CONDITION_NOT_MET_VALUE = 3;
  /**
   * <pre>
   * locationUpdateEvents are not being received according to specification
   * </pre>
   *
   * <code>DATA_RATE_ERROR = 4;</code>
   */
  public static final int DATA_RATE_ERROR_VALUE = 4;
  /**
   * <pre>
   * a timestamp response was not received within the expected timeframe
   * </pre>
   *
   * <code>NO_TIMESTAMP_ANSWER = 5;</code>
   */
  public static final int NO_TIMESTAMP_ANSWER_VALUE = 5;
  /**
   * <pre>
   * difference between clocks of FMS and CSP is too big
   * </pre>
   *
   * <code>TIMEDIFF_TOO_BIG = 6;</code>
   */
  public static final int TIMEDIFF_TOO_BIG_VALUE = 6;
  /**
   * <pre>
   * proto message could not be decoded
   * </pre>
   *
   * <code>INVALID_PROTO = 7;</code>
   */
  public static final int INVALID_PROTO_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ErrorType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ErrorType forNumber(int value) {
    switch (value) {
      case 0: return ERRORTYPE_UNKNOWN;
      case 1: return MISSING_FIELD;
      case 2: return INVALID_FIELD;
      case 3: return PRE_CONDITION_NOT_MET;
      case 4: return DATA_RATE_ERROR;
      case 5: return NO_TIMESTAMP_ANSWER;
      case 6: return TIMEDIFF_TOO_BIG;
      case 7: return INVALID_PROTO;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ErrorType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ErrorType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ErrorType>() {
          public ErrorType findValueByNumber(int number) {
            return ErrorType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return fmsitsinterface.FMSITSInterfaceSpecification.getDescriptor().getEnumTypes().get(1);
  }

  private static final ErrorType[] VALUES = values();

  public static ErrorType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ErrorType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:fmsitsinterface.ErrorType)
}

