// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FMS_ITS_Interface_Specification.proto

package fmsitsinterface;

public interface ErrorMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fmsitsinterface.ErrorMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.fmsitsinterface.ErrorType error_type = 1;</code>
   * @return The enum numeric value on the wire for errorType.
   */
  int getErrorTypeValue();
  /**
   * <code>.fmsitsinterface.ErrorType error_type = 1;</code>
   * @return The errorType.
   */
  fmsitsinterface.ErrorType getErrorType();

  /**
   * <pre>
   * details of the error
   * </pre>
   *
   * <code>string error_message = 2;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <pre>
   * details of the error
   * </pre>
   *
   * <code>string error_message = 2;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <pre>
   * if the error relates to a specific field, the name of the field is added
   * </pre>
   *
   * <code>string related_field = 3;</code>
   * @return The relatedField.
   */
  java.lang.String getRelatedField();
  /**
   * <pre>
   * if the error relates to a specific field, the name of the field is added
   * </pre>
   *
   * <code>string related_field = 3;</code>
   * @return The bytes for relatedField.
   */
  com.google.protobuf.ByteString
      getRelatedFieldBytes();

  /**
   * <pre>
   * the original input message the error is related to
   * </pre>
   *
   * <code>.fmsitsinterface.FmsItsMessage related_message = 4;</code>
   * @return Whether the relatedMessage field is set.
   */
  boolean hasRelatedMessage();
  /**
   * <pre>
   * the original input message the error is related to
   * </pre>
   *
   * <code>.fmsitsinterface.FmsItsMessage related_message = 4;</code>
   * @return The relatedMessage.
   */
  fmsitsinterface.FmsItsMessage getRelatedMessage();
  /**
   * <pre>
   * the original input message the error is related to
   * </pre>
   *
   * <code>.fmsitsinterface.FmsItsMessage related_message = 4;</code>
   */
  fmsitsinterface.FmsItsMessageOrBuilder getRelatedMessageOrBuilder();

  /**
   * <pre>
   * in case the original message could not be parsed, it is returned as raw byte array
   * </pre>
   *
   * <code>bytes related_raw_message = 5;</code>
   * @return The relatedRawMessage.
   */
  com.google.protobuf.ByteString getRelatedRawMessage();
}
