// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FMS_ITS_Interface_Specification.proto

package fmsitsinterface;

/**
 * Protobuf type {@code fmsitsinterface.EventInfo}
 */
public final class EventInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:fmsitsinterface.EventInfo)
    EventInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EventInfo.newBuilder() to construct.
  private EventInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EventInfo() {
    eventText_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EventInfo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return fmsitsinterface.FMSITSInterfaceSpecification.internal_static_fmsitsinterface_EventInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return fmsitsinterface.FMSITSInterfaceSpecification.internal_static_fmsitsinterface_EventInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            fmsitsinterface.EventInfo.class, fmsitsinterface.EventInfo.Builder.class);
  }

  public static final int EVENT_TEXT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object eventText_ = "";
  /**
   * <pre>
   * Textual representation of ITSEventCode.
   * </pre>
   *
   * <code>string event_text = 1;</code>
   * @return The eventText.
   */
  @java.lang.Override
  public java.lang.String getEventText() {
    java.lang.Object ref = eventText_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventText_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Textual representation of ITSEventCode.
   * </pre>
   *
   * <code>string event_text = 1;</code>
   * @return The bytes for eventText.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventTextBytes() {
    java.lang.Object ref = eventText_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCATION_FIELD_NUMBER = 2;
  private fmsitsinterface.Location location_;
  /**
   * <pre>
   * container for location details, compliant with EPSG 4326
   * </pre>
   *
   * <code>.fmsitsinterface.Location location = 2;</code>
   * @return Whether the location field is set.
   */
  @java.lang.Override
  public boolean hasLocation() {
    return location_ != null;
  }
  /**
   * <pre>
   * container for location details, compliant with EPSG 4326
   * </pre>
   *
   * <code>.fmsitsinterface.Location location = 2;</code>
   * @return The location.
   */
  @java.lang.Override
  public fmsitsinterface.Location getLocation() {
    return location_ == null ? fmsitsinterface.Location.getDefaultInstance() : location_;
  }
  /**
   * <pre>
   * container for location details, compliant with EPSG 4326
   * </pre>
   *
   * <code>.fmsitsinterface.Location location = 2;</code>
   */
  @java.lang.Override
  public fmsitsinterface.LocationOrBuilder getLocationOrBuilder() {
    return location_ == null ? fmsitsinterface.Location.getDefaultInstance() : location_;
  }

  public static final int STATIC_EVENT_METADATA_FIELD_NUMBER = 3;
  private fmsitsinterface.StaticEventMetadata staticEventMetadata_;
  /**
   * <pre>
   * Contains other containers for static events.
   * </pre>
   *
   * <code>.fmsitsinterface.StaticEventMetadata static_event_metadata = 3;</code>
   * @return Whether the staticEventMetadata field is set.
   */
  @java.lang.Override
  public boolean hasStaticEventMetadata() {
    return staticEventMetadata_ != null;
  }
  /**
   * <pre>
   * Contains other containers for static events.
   * </pre>
   *
   * <code>.fmsitsinterface.StaticEventMetadata static_event_metadata = 3;</code>
   * @return The staticEventMetadata.
   */
  @java.lang.Override
  public fmsitsinterface.StaticEventMetadata getStaticEventMetadata() {
    return staticEventMetadata_ == null ? fmsitsinterface.StaticEventMetadata.getDefaultInstance() : staticEventMetadata_;
  }
  /**
   * <pre>
   * Contains other containers for static events.
   * </pre>
   *
   * <code>.fmsitsinterface.StaticEventMetadata static_event_metadata = 3;</code>
   */
  @java.lang.Override
  public fmsitsinterface.StaticEventMetadataOrBuilder getStaticEventMetadataOrBuilder() {
    return staticEventMetadata_ == null ? fmsitsinterface.StaticEventMetadata.getDefaultInstance() : staticEventMetadata_;
  }

  public static final int DYNAMIC_EVENT_METADATA_FIELD_NUMBER = 4;
  private fmsitsinterface.DynamicEventMetadata dynamicEventMetadata_;
  /**
   * <pre>
   * Contains other containers for dynamic events, its_event_code EMERGENCY_VEHICLE_APPROACHING, ROAD_INSPECTOR or GHOST_DRIVER_WARNING
   * </pre>
   *
   * <code>.fmsitsinterface.DynamicEventMetadata dynamic_event_metadata = 4;</code>
   * @return Whether the dynamicEventMetadata field is set.
   */
  @java.lang.Override
  public boolean hasDynamicEventMetadata() {
    return dynamicEventMetadata_ != null;
  }
  /**
   * <pre>
   * Contains other containers for dynamic events, its_event_code EMERGENCY_VEHICLE_APPROACHING, ROAD_INSPECTOR or GHOST_DRIVER_WARNING
   * </pre>
   *
   * <code>.fmsitsinterface.DynamicEventMetadata dynamic_event_metadata = 4;</code>
   * @return The dynamicEventMetadata.
   */
  @java.lang.Override
  public fmsitsinterface.DynamicEventMetadata getDynamicEventMetadata() {
    return dynamicEventMetadata_ == null ? fmsitsinterface.DynamicEventMetadata.getDefaultInstance() : dynamicEventMetadata_;
  }
  /**
   * <pre>
   * Contains other containers for dynamic events, its_event_code EMERGENCY_VEHICLE_APPROACHING, ROAD_INSPECTOR or GHOST_DRIVER_WARNING
   * </pre>
   *
   * <code>.fmsitsinterface.DynamicEventMetadata dynamic_event_metadata = 4;</code>
   */
  @java.lang.Override
  public fmsitsinterface.DynamicEventMetadataOrBuilder getDynamicEventMetadataOrBuilder() {
    return dynamicEventMetadata_ == null ? fmsitsinterface.DynamicEventMetadata.getDefaultInstance() : dynamicEventMetadata_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventText_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, eventText_);
    }
    if (location_ != null) {
      output.writeMessage(2, getLocation());
    }
    if (staticEventMetadata_ != null) {
      output.writeMessage(3, getStaticEventMetadata());
    }
    if (dynamicEventMetadata_ != null) {
      output.writeMessage(4, getDynamicEventMetadata());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventText_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, eventText_);
    }
    if (location_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getLocation());
    }
    if (staticEventMetadata_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getStaticEventMetadata());
    }
    if (dynamicEventMetadata_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getDynamicEventMetadata());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof fmsitsinterface.EventInfo)) {
      return super.equals(obj);
    }
    fmsitsinterface.EventInfo other = (fmsitsinterface.EventInfo) obj;

    if (!getEventText()
        .equals(other.getEventText())) return false;
    if (hasLocation() != other.hasLocation()) return false;
    if (hasLocation()) {
      if (!getLocation()
          .equals(other.getLocation())) return false;
    }
    if (hasStaticEventMetadata() != other.hasStaticEventMetadata()) return false;
    if (hasStaticEventMetadata()) {
      if (!getStaticEventMetadata()
          .equals(other.getStaticEventMetadata())) return false;
    }
    if (hasDynamicEventMetadata() != other.hasDynamicEventMetadata()) return false;
    if (hasDynamicEventMetadata()) {
      if (!getDynamicEventMetadata()
          .equals(other.getDynamicEventMetadata())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EVENT_TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getEventText().hashCode();
    if (hasLocation()) {
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
    }
    if (hasStaticEventMetadata()) {
      hash = (37 * hash) + STATIC_EVENT_METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getStaticEventMetadata().hashCode();
    }
    if (hasDynamicEventMetadata()) {
      hash = (37 * hash) + DYNAMIC_EVENT_METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getDynamicEventMetadata().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static fmsitsinterface.EventInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fmsitsinterface.EventInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fmsitsinterface.EventInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fmsitsinterface.EventInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fmsitsinterface.EventInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fmsitsinterface.EventInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fmsitsinterface.EventInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fmsitsinterface.EventInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static fmsitsinterface.EventInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static fmsitsinterface.EventInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static fmsitsinterface.EventInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fmsitsinterface.EventInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(fmsitsinterface.EventInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fmsitsinterface.EventInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fmsitsinterface.EventInfo)
      fmsitsinterface.EventInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fmsitsinterface.FMSITSInterfaceSpecification.internal_static_fmsitsinterface_EventInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fmsitsinterface.FMSITSInterfaceSpecification.internal_static_fmsitsinterface_EventInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fmsitsinterface.EventInfo.class, fmsitsinterface.EventInfo.Builder.class);
    }

    // Construct using fmsitsinterface.EventInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      eventText_ = "";
      location_ = null;
      if (locationBuilder_ != null) {
        locationBuilder_.dispose();
        locationBuilder_ = null;
      }
      staticEventMetadata_ = null;
      if (staticEventMetadataBuilder_ != null) {
        staticEventMetadataBuilder_.dispose();
        staticEventMetadataBuilder_ = null;
      }
      dynamicEventMetadata_ = null;
      if (dynamicEventMetadataBuilder_ != null) {
        dynamicEventMetadataBuilder_.dispose();
        dynamicEventMetadataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return fmsitsinterface.FMSITSInterfaceSpecification.internal_static_fmsitsinterface_EventInfo_descriptor;
    }

    @java.lang.Override
    public fmsitsinterface.EventInfo getDefaultInstanceForType() {
      return fmsitsinterface.EventInfo.getDefaultInstance();
    }

    @java.lang.Override
    public fmsitsinterface.EventInfo build() {
      fmsitsinterface.EventInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public fmsitsinterface.EventInfo buildPartial() {
      fmsitsinterface.EventInfo result = new fmsitsinterface.EventInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(fmsitsinterface.EventInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.eventText_ = eventText_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.location_ = locationBuilder_ == null
            ? location_
            : locationBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.staticEventMetadata_ = staticEventMetadataBuilder_ == null
            ? staticEventMetadata_
            : staticEventMetadataBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.dynamicEventMetadata_ = dynamicEventMetadataBuilder_ == null
            ? dynamicEventMetadata_
            : dynamicEventMetadataBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof fmsitsinterface.EventInfo) {
        return mergeFrom((fmsitsinterface.EventInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(fmsitsinterface.EventInfo other) {
      if (other == fmsitsinterface.EventInfo.getDefaultInstance()) return this;
      if (!other.getEventText().isEmpty()) {
        eventText_ = other.eventText_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasLocation()) {
        mergeLocation(other.getLocation());
      }
      if (other.hasStaticEventMetadata()) {
        mergeStaticEventMetadata(other.getStaticEventMetadata());
      }
      if (other.hasDynamicEventMetadata()) {
        mergeDynamicEventMetadata(other.getDynamicEventMetadata());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              eventText_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getLocationFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getStaticEventMetadataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getDynamicEventMetadataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object eventText_ = "";
    /**
     * <pre>
     * Textual representation of ITSEventCode.
     * </pre>
     *
     * <code>string event_text = 1;</code>
     * @return The eventText.
     */
    public java.lang.String getEventText() {
      java.lang.Object ref = eventText_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventText_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Textual representation of ITSEventCode.
     * </pre>
     *
     * <code>string event_text = 1;</code>
     * @return The bytes for eventText.
     */
    public com.google.protobuf.ByteString
        getEventTextBytes() {
      java.lang.Object ref = eventText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Textual representation of ITSEventCode.
     * </pre>
     *
     * <code>string event_text = 1;</code>
     * @param value The eventText to set.
     * @return This builder for chaining.
     */
    public Builder setEventText(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      eventText_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Textual representation of ITSEventCode.
     * </pre>
     *
     * <code>string event_text = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventText() {
      eventText_ = getDefaultInstance().getEventText();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Textual representation of ITSEventCode.
     * </pre>
     *
     * <code>string event_text = 1;</code>
     * @param value The bytes for eventText to set.
     * @return This builder for chaining.
     */
    public Builder setEventTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eventText_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private fmsitsinterface.Location location_;
    private com.google.protobuf.SingleFieldBuilderV3<
        fmsitsinterface.Location, fmsitsinterface.Location.Builder, fmsitsinterface.LocationOrBuilder> locationBuilder_;
    /**
     * <pre>
     * container for location details, compliant with EPSG 4326
     * </pre>
     *
     * <code>.fmsitsinterface.Location location = 2;</code>
     * @return Whether the location field is set.
     */
    public boolean hasLocation() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * container for location details, compliant with EPSG 4326
     * </pre>
     *
     * <code>.fmsitsinterface.Location location = 2;</code>
     * @return The location.
     */
    public fmsitsinterface.Location getLocation() {
      if (locationBuilder_ == null) {
        return location_ == null ? fmsitsinterface.Location.getDefaultInstance() : location_;
      } else {
        return locationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * container for location details, compliant with EPSG 4326
     * </pre>
     *
     * <code>.fmsitsinterface.Location location = 2;</code>
     */
    public Builder setLocation(fmsitsinterface.Location value) {
      if (locationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        location_ = value;
      } else {
        locationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * container for location details, compliant with EPSG 4326
     * </pre>
     *
     * <code>.fmsitsinterface.Location location = 2;</code>
     */
    public Builder setLocation(
        fmsitsinterface.Location.Builder builderForValue) {
      if (locationBuilder_ == null) {
        location_ = builderForValue.build();
      } else {
        locationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * container for location details, compliant with EPSG 4326
     * </pre>
     *
     * <code>.fmsitsinterface.Location location = 2;</code>
     */
    public Builder mergeLocation(fmsitsinterface.Location value) {
      if (locationBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          location_ != null &&
          location_ != fmsitsinterface.Location.getDefaultInstance()) {
          getLocationBuilder().mergeFrom(value);
        } else {
          location_ = value;
        }
      } else {
        locationBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * container for location details, compliant with EPSG 4326
     * </pre>
     *
     * <code>.fmsitsinterface.Location location = 2;</code>
     */
    public Builder clearLocation() {
      bitField0_ = (bitField0_ & ~0x00000002);
      location_ = null;
      if (locationBuilder_ != null) {
        locationBuilder_.dispose();
        locationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * container for location details, compliant with EPSG 4326
     * </pre>
     *
     * <code>.fmsitsinterface.Location location = 2;</code>
     */
    public fmsitsinterface.Location.Builder getLocationBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getLocationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * container for location details, compliant with EPSG 4326
     * </pre>
     *
     * <code>.fmsitsinterface.Location location = 2;</code>
     */
    public fmsitsinterface.LocationOrBuilder getLocationOrBuilder() {
      if (locationBuilder_ != null) {
        return locationBuilder_.getMessageOrBuilder();
      } else {
        return location_ == null ?
            fmsitsinterface.Location.getDefaultInstance() : location_;
      }
    }
    /**
     * <pre>
     * container for location details, compliant with EPSG 4326
     * </pre>
     *
     * <code>.fmsitsinterface.Location location = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fmsitsinterface.Location, fmsitsinterface.Location.Builder, fmsitsinterface.LocationOrBuilder> 
        getLocationFieldBuilder() {
      if (locationBuilder_ == null) {
        locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fmsitsinterface.Location, fmsitsinterface.Location.Builder, fmsitsinterface.LocationOrBuilder>(
                getLocation(),
                getParentForChildren(),
                isClean());
        location_ = null;
      }
      return locationBuilder_;
    }

    private fmsitsinterface.StaticEventMetadata staticEventMetadata_;
    private com.google.protobuf.SingleFieldBuilderV3<
        fmsitsinterface.StaticEventMetadata, fmsitsinterface.StaticEventMetadata.Builder, fmsitsinterface.StaticEventMetadataOrBuilder> staticEventMetadataBuilder_;
    /**
     * <pre>
     * Contains other containers for static events.
     * </pre>
     *
     * <code>.fmsitsinterface.StaticEventMetadata static_event_metadata = 3;</code>
     * @return Whether the staticEventMetadata field is set.
     */
    public boolean hasStaticEventMetadata() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Contains other containers for static events.
     * </pre>
     *
     * <code>.fmsitsinterface.StaticEventMetadata static_event_metadata = 3;</code>
     * @return The staticEventMetadata.
     */
    public fmsitsinterface.StaticEventMetadata getStaticEventMetadata() {
      if (staticEventMetadataBuilder_ == null) {
        return staticEventMetadata_ == null ? fmsitsinterface.StaticEventMetadata.getDefaultInstance() : staticEventMetadata_;
      } else {
        return staticEventMetadataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Contains other containers for static events.
     * </pre>
     *
     * <code>.fmsitsinterface.StaticEventMetadata static_event_metadata = 3;</code>
     */
    public Builder setStaticEventMetadata(fmsitsinterface.StaticEventMetadata value) {
      if (staticEventMetadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        staticEventMetadata_ = value;
      } else {
        staticEventMetadataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contains other containers for static events.
     * </pre>
     *
     * <code>.fmsitsinterface.StaticEventMetadata static_event_metadata = 3;</code>
     */
    public Builder setStaticEventMetadata(
        fmsitsinterface.StaticEventMetadata.Builder builderForValue) {
      if (staticEventMetadataBuilder_ == null) {
        staticEventMetadata_ = builderForValue.build();
      } else {
        staticEventMetadataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contains other containers for static events.
     * </pre>
     *
     * <code>.fmsitsinterface.StaticEventMetadata static_event_metadata = 3;</code>
     */
    public Builder mergeStaticEventMetadata(fmsitsinterface.StaticEventMetadata value) {
      if (staticEventMetadataBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          staticEventMetadata_ != null &&
          staticEventMetadata_ != fmsitsinterface.StaticEventMetadata.getDefaultInstance()) {
          getStaticEventMetadataBuilder().mergeFrom(value);
        } else {
          staticEventMetadata_ = value;
        }
      } else {
        staticEventMetadataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contains other containers for static events.
     * </pre>
     *
     * <code>.fmsitsinterface.StaticEventMetadata static_event_metadata = 3;</code>
     */
    public Builder clearStaticEventMetadata() {
      bitField0_ = (bitField0_ & ~0x00000004);
      staticEventMetadata_ = null;
      if (staticEventMetadataBuilder_ != null) {
        staticEventMetadataBuilder_.dispose();
        staticEventMetadataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contains other containers for static events.
     * </pre>
     *
     * <code>.fmsitsinterface.StaticEventMetadata static_event_metadata = 3;</code>
     */
    public fmsitsinterface.StaticEventMetadata.Builder getStaticEventMetadataBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getStaticEventMetadataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Contains other containers for static events.
     * </pre>
     *
     * <code>.fmsitsinterface.StaticEventMetadata static_event_metadata = 3;</code>
     */
    public fmsitsinterface.StaticEventMetadataOrBuilder getStaticEventMetadataOrBuilder() {
      if (staticEventMetadataBuilder_ != null) {
        return staticEventMetadataBuilder_.getMessageOrBuilder();
      } else {
        return staticEventMetadata_ == null ?
            fmsitsinterface.StaticEventMetadata.getDefaultInstance() : staticEventMetadata_;
      }
    }
    /**
     * <pre>
     * Contains other containers for static events.
     * </pre>
     *
     * <code>.fmsitsinterface.StaticEventMetadata static_event_metadata = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fmsitsinterface.StaticEventMetadata, fmsitsinterface.StaticEventMetadata.Builder, fmsitsinterface.StaticEventMetadataOrBuilder> 
        getStaticEventMetadataFieldBuilder() {
      if (staticEventMetadataBuilder_ == null) {
        staticEventMetadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fmsitsinterface.StaticEventMetadata, fmsitsinterface.StaticEventMetadata.Builder, fmsitsinterface.StaticEventMetadataOrBuilder>(
                getStaticEventMetadata(),
                getParentForChildren(),
                isClean());
        staticEventMetadata_ = null;
      }
      return staticEventMetadataBuilder_;
    }

    private fmsitsinterface.DynamicEventMetadata dynamicEventMetadata_;
    private com.google.protobuf.SingleFieldBuilderV3<
        fmsitsinterface.DynamicEventMetadata, fmsitsinterface.DynamicEventMetadata.Builder, fmsitsinterface.DynamicEventMetadataOrBuilder> dynamicEventMetadataBuilder_;
    /**
     * <pre>
     * Contains other containers for dynamic events, its_event_code EMERGENCY_VEHICLE_APPROACHING, ROAD_INSPECTOR or GHOST_DRIVER_WARNING
     * </pre>
     *
     * <code>.fmsitsinterface.DynamicEventMetadata dynamic_event_metadata = 4;</code>
     * @return Whether the dynamicEventMetadata field is set.
     */
    public boolean hasDynamicEventMetadata() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Contains other containers for dynamic events, its_event_code EMERGENCY_VEHICLE_APPROACHING, ROAD_INSPECTOR or GHOST_DRIVER_WARNING
     * </pre>
     *
     * <code>.fmsitsinterface.DynamicEventMetadata dynamic_event_metadata = 4;</code>
     * @return The dynamicEventMetadata.
     */
    public fmsitsinterface.DynamicEventMetadata getDynamicEventMetadata() {
      if (dynamicEventMetadataBuilder_ == null) {
        return dynamicEventMetadata_ == null ? fmsitsinterface.DynamicEventMetadata.getDefaultInstance() : dynamicEventMetadata_;
      } else {
        return dynamicEventMetadataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Contains other containers for dynamic events, its_event_code EMERGENCY_VEHICLE_APPROACHING, ROAD_INSPECTOR or GHOST_DRIVER_WARNING
     * </pre>
     *
     * <code>.fmsitsinterface.DynamicEventMetadata dynamic_event_metadata = 4;</code>
     */
    public Builder setDynamicEventMetadata(fmsitsinterface.DynamicEventMetadata value) {
      if (dynamicEventMetadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dynamicEventMetadata_ = value;
      } else {
        dynamicEventMetadataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contains other containers for dynamic events, its_event_code EMERGENCY_VEHICLE_APPROACHING, ROAD_INSPECTOR or GHOST_DRIVER_WARNING
     * </pre>
     *
     * <code>.fmsitsinterface.DynamicEventMetadata dynamic_event_metadata = 4;</code>
     */
    public Builder setDynamicEventMetadata(
        fmsitsinterface.DynamicEventMetadata.Builder builderForValue) {
      if (dynamicEventMetadataBuilder_ == null) {
        dynamicEventMetadata_ = builderForValue.build();
      } else {
        dynamicEventMetadataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contains other containers for dynamic events, its_event_code EMERGENCY_VEHICLE_APPROACHING, ROAD_INSPECTOR or GHOST_DRIVER_WARNING
     * </pre>
     *
     * <code>.fmsitsinterface.DynamicEventMetadata dynamic_event_metadata = 4;</code>
     */
    public Builder mergeDynamicEventMetadata(fmsitsinterface.DynamicEventMetadata value) {
      if (dynamicEventMetadataBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          dynamicEventMetadata_ != null &&
          dynamicEventMetadata_ != fmsitsinterface.DynamicEventMetadata.getDefaultInstance()) {
          getDynamicEventMetadataBuilder().mergeFrom(value);
        } else {
          dynamicEventMetadata_ = value;
        }
      } else {
        dynamicEventMetadataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contains other containers for dynamic events, its_event_code EMERGENCY_VEHICLE_APPROACHING, ROAD_INSPECTOR or GHOST_DRIVER_WARNING
     * </pre>
     *
     * <code>.fmsitsinterface.DynamicEventMetadata dynamic_event_metadata = 4;</code>
     */
    public Builder clearDynamicEventMetadata() {
      bitField0_ = (bitField0_ & ~0x00000008);
      dynamicEventMetadata_ = null;
      if (dynamicEventMetadataBuilder_ != null) {
        dynamicEventMetadataBuilder_.dispose();
        dynamicEventMetadataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contains other containers for dynamic events, its_event_code EMERGENCY_VEHICLE_APPROACHING, ROAD_INSPECTOR or GHOST_DRIVER_WARNING
     * </pre>
     *
     * <code>.fmsitsinterface.DynamicEventMetadata dynamic_event_metadata = 4;</code>
     */
    public fmsitsinterface.DynamicEventMetadata.Builder getDynamicEventMetadataBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getDynamicEventMetadataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Contains other containers for dynamic events, its_event_code EMERGENCY_VEHICLE_APPROACHING, ROAD_INSPECTOR or GHOST_DRIVER_WARNING
     * </pre>
     *
     * <code>.fmsitsinterface.DynamicEventMetadata dynamic_event_metadata = 4;</code>
     */
    public fmsitsinterface.DynamicEventMetadataOrBuilder getDynamicEventMetadataOrBuilder() {
      if (dynamicEventMetadataBuilder_ != null) {
        return dynamicEventMetadataBuilder_.getMessageOrBuilder();
      } else {
        return dynamicEventMetadata_ == null ?
            fmsitsinterface.DynamicEventMetadata.getDefaultInstance() : dynamicEventMetadata_;
      }
    }
    /**
     * <pre>
     * Contains other containers for dynamic events, its_event_code EMERGENCY_VEHICLE_APPROACHING, ROAD_INSPECTOR or GHOST_DRIVER_WARNING
     * </pre>
     *
     * <code>.fmsitsinterface.DynamicEventMetadata dynamic_event_metadata = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fmsitsinterface.DynamicEventMetadata, fmsitsinterface.DynamicEventMetadata.Builder, fmsitsinterface.DynamicEventMetadataOrBuilder> 
        getDynamicEventMetadataFieldBuilder() {
      if (dynamicEventMetadataBuilder_ == null) {
        dynamicEventMetadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fmsitsinterface.DynamicEventMetadata, fmsitsinterface.DynamicEventMetadata.Builder, fmsitsinterface.DynamicEventMetadataOrBuilder>(
                getDynamicEventMetadata(),
                getParentForChildren(),
                isClean());
        dynamicEventMetadata_ = null;
      }
      return dynamicEventMetadataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:fmsitsinterface.EventInfo)
  }

  // @@protoc_insertion_point(class_scope:fmsitsinterface.EventInfo)
  private static final fmsitsinterface.EventInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new fmsitsinterface.EventInfo();
  }

  public static fmsitsinterface.EventInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EventInfo>
      PARSER = new com.google.protobuf.AbstractParser<EventInfo>() {
    @java.lang.Override
    public EventInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EventInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EventInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public fmsitsinterface.EventInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

