// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FMS_ITS_Interface_Specification.proto

package fmsitsinterface;

public interface EventInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fmsitsinterface.EventInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Textual representation of ITSEventCode.
   * </pre>
   *
   * <code>string event_text = 1;</code>
   * @return The eventText.
   */
  java.lang.String getEventText();
  /**
   * <pre>
   * Textual representation of ITSEventCode.
   * </pre>
   *
   * <code>string event_text = 1;</code>
   * @return The bytes for eventText.
   */
  com.google.protobuf.ByteString
      getEventTextBytes();

  /**
   * <pre>
   * container for location details, compliant with EPSG 4326
   * </pre>
   *
   * <code>.fmsitsinterface.Location location = 2;</code>
   * @return Whether the location field is set.
   */
  boolean hasLocation();
  /**
   * <pre>
   * container for location details, compliant with EPSG 4326
   * </pre>
   *
   * <code>.fmsitsinterface.Location location = 2;</code>
   * @return The location.
   */
  fmsitsinterface.Location getLocation();
  /**
   * <pre>
   * container for location details, compliant with EPSG 4326
   * </pre>
   *
   * <code>.fmsitsinterface.Location location = 2;</code>
   */
  fmsitsinterface.LocationOrBuilder getLocationOrBuilder();

  /**
   * <pre>
   * Contains other containers for static events.
   * </pre>
   *
   * <code>.fmsitsinterface.StaticEventMetadata static_event_metadata = 3;</code>
   * @return Whether the staticEventMetadata field is set.
   */
  boolean hasStaticEventMetadata();
  /**
   * <pre>
   * Contains other containers for static events.
   * </pre>
   *
   * <code>.fmsitsinterface.StaticEventMetadata static_event_metadata = 3;</code>
   * @return The staticEventMetadata.
   */
  fmsitsinterface.StaticEventMetadata getStaticEventMetadata();
  /**
   * <pre>
   * Contains other containers for static events.
   * </pre>
   *
   * <code>.fmsitsinterface.StaticEventMetadata static_event_metadata = 3;</code>
   */
  fmsitsinterface.StaticEventMetadataOrBuilder getStaticEventMetadataOrBuilder();

  /**
   * <pre>
   * Contains other containers for dynamic events, its_event_code EMERGENCY_VEHICLE_APPROACHING, ROAD_INSPECTOR or GHOST_DRIVER_WARNING
   * </pre>
   *
   * <code>.fmsitsinterface.DynamicEventMetadata dynamic_event_metadata = 4;</code>
   * @return Whether the dynamicEventMetadata field is set.
   */
  boolean hasDynamicEventMetadata();
  /**
   * <pre>
   * Contains other containers for dynamic events, its_event_code EMERGENCY_VEHICLE_APPROACHING, ROAD_INSPECTOR or GHOST_DRIVER_WARNING
   * </pre>
   *
   * <code>.fmsitsinterface.DynamicEventMetadata dynamic_event_metadata = 4;</code>
   * @return The dynamicEventMetadata.
   */
  fmsitsinterface.DynamicEventMetadata getDynamicEventMetadata();
  /**
   * <pre>
   * Contains other containers for dynamic events, its_event_code EMERGENCY_VEHICLE_APPROACHING, ROAD_INSPECTOR or GHOST_DRIVER_WARNING
   * </pre>
   *
   * <code>.fmsitsinterface.DynamicEventMetadata dynamic_event_metadata = 4;</code>
   */
  fmsitsinterface.DynamicEventMetadataOrBuilder getDynamicEventMetadataOrBuilder();
}
