// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FMS_ITS_Interface_Specification.proto

package fmsitsinterface;

public final class FMSITSInterfaceSpecification {
  private FMSITSInterfaceSpecification() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_FmsItsMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_FmsItsMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_FmsItsContainer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_FmsItsContainer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_ErrorMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_ErrorMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_TimestampMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_TimestampMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_MeasurementType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_MeasurementType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_InfoContainer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_InfoContainer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_ContentContainer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_ContentContainer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_EventInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_EventInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_Point_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_Point_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_Location_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_Location_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_StaticEventMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_StaticEventMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_RoadConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_RoadConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_OvertakingInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_OvertakingInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_SpeedInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_SpeedInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_IvriContainer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_IvriContainer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_PriorityContainer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_PriorityContainer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_TrafficLightStateInformation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_TrafficLightStateInformation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_TrafficLightTimingInformation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_TrafficLightTimingInformation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_TrafficLightSpeedAdvice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_TrafficLightSpeedAdvice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_LaneInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_LaneInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_Maneuver_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_Maneuver_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_SensorInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_SensorInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_TirePressure_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_TirePressure_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_Anomalies_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_Anomalies_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_VehicleWeight_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_VehicleWeight_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_WeightMeasurements_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_WeightMeasurements_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_DynamicEventMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_DynamicEventMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_LocationUpdateEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_LocationUpdateEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fmsitsinterface_LocationUpdateEvent_GeoReference_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fmsitsinterface_LocationUpdateEvent_GeoReference_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%FMS_ITS_Interface_Specification.proto\022" +
      "\017fmsitsinterface\032\037google/protobuf/timest" +
      "amp.proto\"\214\001\n\rFmsItsMessage\0222\n\014message_t" +
      "ype\030\001 \001(\0162\034.fmsitsinterface.MessageType\022" +
      "\022\n\nvehicle_id\030\002 \001(\t\0223\n\tcontainer\030\003 \001(\0132 " +
      ".fmsitsinterface.FmsItsContainer\"\272\002\n\017Fms" +
      "ItsContainer\022<\n\021timestamp_message\030\001 \001(\0132" +
      "!.fmsitsinterface.TimestampMessage\0226\n\016in" +
      "fo_container\030\002 \001(\0132\036.fmsitsinterface.Inf" +
      "oContainer\022<\n\021content_container\030\003 \001(\0132!." +
      "fmsitsinterface.ContentContainer\022=\n\017loca" +
      "tion_update\030\004 \001(\0132$.fmsitsinterface.Loca" +
      "tionUpdateEvent\0224\n\rerror_message\030\005 \001(\0132\035" +
      ".fmsitsinterface.ErrorMessage\"\302\001\n\014ErrorM" +
      "essage\022.\n\nerror_type\030\001 \001(\0162\032.fmsitsinter" +
      "face.ErrorType\022\025\n\rerror_message\030\002 \001(\t\022\025\n" +
      "\rrelated_field\030\003 \001(\t\0227\n\017related_message\030" +
      "\004 \001(\0132\036.fmsitsinterface.FmsItsMessage\022\033\n" +
      "\023related_raw_message\030\005 \001(\014\"\276\001\n\020Timestamp" +
      "Message\0228\n\024request_transmission\030\001 \001(\0132\032." +
      "google.protobuf.Timestamp\0225\n\021request_rec" +
      "eption\030\002 \001(\0132\032.google.protobuf.Timestamp" +
      "\0229\n\025response_transmission\030\003 \001(\0132\032.google" +
      ".protobuf.Timestamp\"P\n\017MeasurementType\022\r" +
      "\n\005value\030\001 \001(\005\022.\n\004unit\030\002 \001(\0162 .fmsitsinte" +
      "rface.MeasurementUnit\"\241\002\n\rInfoContainer\022" +
      "\016\n\006author\030\001 \001(\t\022\020\n\010event_id\030\002 \001(\t\022@\n\014mes" +
      "sage_type\030\003 \001(\0162*.fmsitsinterface.InfoCo" +
      "ntainer.MessageType\022\025\n\revent_version\030\004 \001" +
      "(\005\0221\n\rcreation_time\030\005 \001(\0132\032.google.proto" +
      "buf.Timestamp\022\030\n\020desired_interval\030\006 \001(\005\"" +
      "H\n\013MessageType\022\030\n\024UNKNOWN_MESSAGE_TYPE\020\000" +
      "\022\007\n\003NEW\020\001\022\n\n\006UPDATE\020\002\022\n\n\006DELETE\020\003\"y\n\020Con" +
      "tentContainer\0225\n\016its_event_code\030\001 \001(\0162\035." +
      "fmsitsinterface.ItsEventCode\022.\n\nevent_in" +
      "fo\030\002 \001(\0132\032.fmsitsinterface.EventInfo\"\330\001\n" +
      "\tEventInfo\022\022\n\nevent_text\030\001 \001(\t\022+\n\010locati" +
      "on\030\002 \001(\0132\031.fmsitsinterface.Location\022C\n\025s" +
      "tatic_event_metadata\030\003 \001(\0132$.fmsitsinter" +
      "face.StaticEventMetadata\022E\n\026dynamic_even" +
      "t_metadata\030\004 \001(\0132%.fmsitsinterface.Dynam" +
      "icEventMetadata\",\n\005Point\022\020\n\010latitude\030\001 \001" +
      "(\002\022\021\n\tlongitude\030\002 \001(\002\"\211\002\n\010Location\022+\n\013co" +
      "ordinates\030\001 \003(\0132\026.fmsitsinterface.Point\022" +
      "C\n\020coordinates_type\030\002 \001(\0162).fmsitsinterf" +
      "ace.Location.CoordinatesType\0221\n\007heading\030" +
      "\003 \001(\0132 .fmsitsinterface.MeasurementType\"" +
      "X\n\017CoordinatesType\022\034\n\030UNKNOWN_COORDINATE" +
      "S_TYPE\020\000\022\017\n\013LINE_STRING\020\001\022\t\n\005POINT\020\002\022\013\n\007" +
      "POLYGON\020\003\"\272\004\n\023StaticEventMetadata\022R\n\022wea" +
      "ther_conditions\030\001 \001(\01626.fmsitsinterface." +
      "StaticEventMetadata.WeatherConditions\022>\n" +
      "\022road_configuration\030\002 \001(\0132\".fmsitsinterf" +
      "ace.RoadConfiguration\022.\n\nspeed_info\030\003 \001(" +
      "\0132\032.fmsitsinterface.SpeedInfo\0226\n\016ivri_co" +
      "ntainer\030\004 \001(\0132\036.fmsitsinterface.IvriCont" +
      "ainer\022,\n\tlane_info\030\005 \001(\0132\031.fmsitsinterfa" +
      "ce.LaneInfo\0220\n\013sensor_info\030\006 \001(\0132\033.fmsit" +
      "sinterface.SensorInfo\0228\n\017overtaking_info" +
      "\030\007 \001(\0132\037.fmsitsinterface.OvertakingInfo\"" +
      "\214\001\n\021WeatherConditions\022\035\n\031UNKNOWN_WEATHER" +
      "_CONDITION\020\000\022\016\n\nHEAVY_RAIN\020\001\022\021\n\rSLIPPERY" +
      "_ROAD\020\002\022\007\n\003FOG\020\003\022\016\n\nHEAVY_WIND\020\004\022\022\n\016HEAV" +
      "Y_SNOWFALL\020\005\022\010\n\004HAIL\020\006\"\313\004\n\021RoadConfigura" +
      "tion\022O\n\022road_config_status\030\001 \001(\01623.fmsit" +
      "sinterface.RoadConfiguration.RoadConfigS" +
      "tatus\0223\n\tmax_speed\030\002 \001(\0132 .fmsitsinterfa" +
      "ce.MeasurementType\022S\n\024road_config_locati" +
      "on\030\003 \001(\01625.fmsitsinterface.RoadConfigura" +
      "tion.RoadConfigLocation\022\020\n\010flashing\030\004 \001(" +
      "\010\022\022\n\nred_border\030\005 \001(\010\"\330\001\n\020RoadConfigStat" +
      "us\022\036\n\032UNKNOWN_ROAD_CONFIG_STATUS\020\000\022\010\n\004OP" +
      "EN\020\001\022\n\n\006CLOSED\020\002\022\032\n\026CLOSED_FOR_ALL_TRAFF" +
      "IC\020\002\022\017\n\013MERGE_RIGHT\020\003\022\016\n\nMERGE_LEFT\020\004\022\027\n" +
      "\023END_OF_RESTRICTIONS\020\005\022\022\n\016CLOSED_FOR_YOU" +
      "\020\006\022\025\n\021CHANGED_MAX_SPEED\020\007\022\t\n\005BLANK\020\010\032\002\020\001" +
      "\"Z\n\022RoadConfigLocation\022\024\n\020UNKNOWN_LOCATI" +
      "ON\020\000\022\027\n\023LOCATION_DOWNSTREAM\020\001\022\025\n\021LOCATIO" +
      "N_UPSTREAM\020\002\"\240\002\n\016OvertakingInfo\022M\n\016appli" +
      "cable_for\030\001 \003(\01625.fmsitsinterface.Overta" +
      "kingInfo.ApplicableVehicleType\022I\n\nexcept" +
      "_for\030\002 \003(\01625.fmsitsinterface.OvertakingI" +
      "nfo.ApplicableVehicleType\"t\n\025ApplicableV" +
      "ehicleType\022#\n\037UNKNOWN_APPLICABLE_VEHICLE" +
      "_TYPE\020\000\022\021\n\rALL_MOTORIZED\020\001\022\007\n\003HGV\020\002\022\017\n\013A" +
      "GRICULTURE\020\003\022\t\n\005MOPED\020\004\"{\n\tSpeedInfo\022\033\n\023" +
      "maximum_speed_limit\030\001 \001(\005\022\025\n\roptimal_spe" +
      "ed\030\002 \001(\005\022:\n\020speed_limit_unit\030\003 \001(\0162 .fms" +
      "itsinterface.MeasurementUnit\"\317\002\n\rIvriCon" +
      "tainer\022>\n\022priority_container\030\001 \001(\0132\".fms" +
      "itsinterface.PriorityContainer\022V\n\037traffi" +
      "c_light_state_information\030\002 \001(\0132-.fmsits" +
      "interface.TrafficLightStateInformation\022X" +
      "\n traffic_light_timing_information\030\003 \001(\013" +
      "2..fmsitsinterface.TrafficLightTimingInf" +
      "ormation\022L\n\032traffic_light_speed_advice\030\004" +
      " \001(\0132(.fmsitsinterface.TrafficLightSpeed" +
      "Advice\"a\n\021PriorityContainer\022\016\n\006status\030\001 " +
      "\001(\t\022+\n\010maneuver\030\002 \001(\0132\031.fmsitsinterface." +
      "Maneuver\022\017\n\007lane_id\030\003 \001(\005\"\236\004\n\034TrafficLig" +
      "htStateInformation\022Q\n\rcurrent_state\030\001 \001(" +
      "\0162:.fmsitsinterface.TrafficLightStateInf" +
      "ormation.CurrentState\022B\n\005arrow\030\002 \001(\01623.f" +
      "msitsinterface.TrafficLightStateInformat" +
      "ion.Arrow\022H\n\010movement\030\003 \001(\01626.fmsitsinte" +
      "rface.TrafficLightStateInformation.Movem" +
      "ent\"{\n\014CurrentState\022\037\n\033UNKNOWN_TRAFFIC_L" +
      "IGHT_STATE\020\000\022\007\n\003RED\020\001\022\t\n\005AMBER\020\002\022\t\n\005GREE" +
      "N\020\003\022\023\n\017ORANGE_FLASHING\020\004\022\010\n\004DARK\020\005\022\014\n\010NO" +
      "_LIGHT\020\006\"_\n\005Arrow\022\021\n\rUNKNOWN_ARROW\020\000\022\016\n\n" +
      "ARROW_NONE\020\001\022\016\n\nARROW_LEFT\020\002\022\017\n\013ARROW_RI" +
      "GHT\020\003\022\022\n\016ARROW_STRAIGHT\020\004\"?\n\010Movement\022\024\n" +
      "\020UNKNOWN_MOVEMENT\020\000\022\r\n\tPROTECTED\020\001\022\016\n\nPE" +
      "RMISSIVE\020\002\"\264\001\n\035TrafficLightTimingInforma" +
      "tion\0220\n\014min_end_time\030\001 \001(\0132\032.google.prot" +
      "obuf.Timestamp\0220\n\014max_end_time\030\002 \001(\0132\032.g" +
      "oogle.protobuf.Timestamp\022/\n\013likely_time\030" +
      "\003 \001(\0132\032.google.protobuf.Timestamp\">\n\027Tra" +
      "fficLightSpeedAdvice\022\016\n\006advice\030\001 \001(\t\022\023\n\013" +
      "advice_type\030\002 \001(\t\"^\n\010LaneInfo\022\023\n\013max_lan" +
      "e_id\030\001 \001(\005\022\017\n\007lane_id\030\002 \001(\005\022,\n\tmaneuvers" +
      "\030\003 \003(\0132\031.fmsitsinterface.Maneuver\"\274\001\n\010Ma" +
      "neuver\0226\n\tdirection\030\001 \003(\0162#.fmsitsinterf" +
      "ace.Maneuver.Direction\022\024\n\014always_yield\030\002" +
      " \001(\010\"b\n\tDirection\022\025\n\021UNKNOWN_DIRECTION\020\000" +
      "\022\014\n\010STRAIGHT\020\001\022\010\n\004LEFT\020\002\022\t\n\005RIGHT\020\003\022\n\n\006U" +
      "_TURN\020\004\022\017\n\013UNSPECIFIED\020\005\"\264\001\n\nSensorInfo\022" +
      "4\n\rtire_pressure\030\001 \001(\0132\035.fmsitsinterface" +
      ".TirePressure\0226\n\016vehicle_weight\030\002 \001(\0132\036." +
      "fmsitsinterface.VehicleWeight\0228\n\016vehicle" +
      "_height\030\003 \001(\0132 .fmsitsinterface.Measurem" +
      "entType\"\362\001\n\014TirePressure\022G\n\006status\030\001 \001(\016" +
      "27.fmsitsinterface.TirePressure.VehicleT" +
      "irePressureStatus\022\022\n\naxle_count\030\002 \001(\005\022-\n" +
      "\tanomalies\030\003 \003(\0132\032.fmsitsinterface.Anoma" +
      "lies\"V\n\031VehicleTirePressureStatus\022\022\n\016UNK" +
      "NOWN_STATUS\020\000\022\006\n\002OK\020\001\022\017\n\013NOK_SUSPECT\020\002\022\014" +
      "\n\010NOK_FLAT\020\003\"\354\001\n\tAnomalies\022\014\n\004axle\030\001 \001(\005" +
      "\022-\n\004side\030\002 \001(\0162\037.fmsitsinterface.Anomali" +
      "es.Side\022:\n\013measurement\030\003 \001(\0162%.fmsitsint" +
      "erface.Anomalies.TireStatus\"-\n\004Side\022\020\n\014U" +
      "NKNOWN_SIDE\020\000\022\010\n\004LEFT\020\001\022\t\n\005RIGHT\020\002\"7\n\nTi" +
      "reStatus\022\022\n\016UNKNOWN_STATUS\020\000\022\010\n\004FLAT\020\001\022\013" +
      "\n\007SUSPECT\020\002\"e\n\rVehicleWeight\022\022\n\naxle_cou" +
      "nt\030\001 \001(\005\022@\n\023weight_measurements\030\002 \003(\0132#." +
      "fmsitsinterface.WeightMeasurements\"T\n\022We" +
      "ightMeasurements\022\014\n\004axle\030\001 \001(\005\0220\n\006weight" +
      "\030\002 \001(\0132 .fmsitsinterface.MeasurementType" +
      "\"\206\001\n\024DynamicEventMetadata\0225\n\013event_speed" +
      "\030\001 \001(\0132 .fmsitsinterface.MeasurementType" +
      "\0227\n\revent_heading\030\002 \001(\0132 .fmsitsinterfac" +
      "e.MeasurementType\"\375\004\n\023LocationUpdateEven" +
      "t\022\n\n\002id\030\001 \001(\t\0221\n\rcreation_date\030\002 \001(\0132\032.g" +
      "oogle.protobuf.Timestamp\022H\n\rgeo_referenc" +
      "e\030\003 \001(\01321.fmsitsinterface.LocationUpdate" +
      "Event.GeoReference\022/\n\005speed\030\004 \001(\0132 .fmsi" +
      "tsinterface.MeasurementType\0221\n\007heading\030\005" +
      " \001(\0132 .fmsitsinterface.MeasurementType\022A" +
      "\n\tlifecycle\030\006 \001(\0162..fmsitsinterface.Loca" +
      "tionUpdateEvent.LifeCycle\022/\n\013device_date" +
      "\030\007 \001(\0132\032.google.protobuf.Timestamp\022\023\n\013gp" +
      "s_quality\030\010 \001(\002\032m\n\014GeoReference\022\013\n\003lat\030\001" +
      " \001(\001\022\013\n\003lon\030\002 \001(\001\022C\n\004type\030\003 \001(\01625.fmsits" +
      "interface.LocationUpdateEvent.GeoReferen" +
      "ceType\"Q\n\020GeoReferenceType\022\034\n\030GEOREFEREN" +
      "CETYPE_UNKNOWN\020\000\022\037\n\033LAT_LON_POINT_GEO_RE" +
      "FERENCE\020\001\".\n\tLifeCycle\022\025\n\021LIFECYCLE_UNKN" +
      "OWN\020\000\022\n\n\006ACTUAL\020\001*x\n\013MessageType\022\027\n\023MESS" +
      "AGETYPE_UNKNOWN\020\000\022\025\n\021TIMESTAMP_MESSAGE\020\001" +
      "\022\023\n\017LOCATION_UPDATE\020\002\022\021\n\rEVENT_MESSAGE\020\003" +
      "\022\021\n\rERROR_MESSAGE\020\004*\272\001\n\tErrorType\022\025\n\021ERR" +
      "ORTYPE_UNKNOWN\020\000\022\021\n\rMISSING_FIELD\020\001\022\021\n\rI" +
      "NVALID_FIELD\020\002\022\031\n\025PRE_CONDITION_NOT_MET\020" +
      "\003\022\023\n\017DATA_RATE_ERROR\020\004\022\027\n\023NO_TIMESTAMP_A" +
      "NSWER\020\005\022\024\n\020TIMEDIFF_TOO_BIG\020\006\022\021\n\rINVALID" +
      "_PROTO\020\007*\302\001\n\017MeasurementUnit\022\013\n\007UNKNOWN\020" +
      "\000\022\027\n\023KILOMETERS_PER_HOUR\020\n\022\025\n\021METERS_PER" +
      "_SECOND\020\013\022\014\n\010KILOGRAM\020\024\022\t\n\005POUND\020\025\022\t\n\005ME" +
      "TER\020\036\022\016\n\nCENTIMETER\020\037\022\017\n\013MILLISECOND\020(\022\n" +
      "\n\006SECOND\020)\022\n\n\006MINUTE\020*\022\010\n\004HOUR\020+\022\013\n\007DEGR" +
      "EES\0202*\232\005\n\014ItsEventCode\022\032\n\026UNKNOWN_ITS_EV" +
      "ENT_CODE\020\000\022\035\n\031CHANGED_FREQUENCY_REQUEST\020" +
      "\001\022\021\n\rMAXIMUM_SPEED\020e\022\030\n\024ADVISORY_SPEED_L" +
      "IMIT\020f\022\022\n\016OVERTAKING_BAN\020g\022\026\n\022LANE_CONFI" +
      "GURATION\020h\022\017\n\nROAD_WORKS\020\311\001\022\013\n\006EVENTS\020\312\001" +
      "\022\020\n\013PLACEHOLDER\020\313\001\022\020\n\013TRAFFIC_JAM\020\314\001\022\027\n\022" +
      "STATIONARY_VEHICLE\020\315\001\022\r\n\010INCIDENT\020\316\001\022\027\n\022" +
      "WEATHER_CONDITIONS\020\317\001\022\024\n\017OBJECTS_ON_ROAD" +
      "\020\320\001\022\"\n\035EMERGENCY_VEHICLE_APPROACHING\020\321\001\022" +
      "\023\n\016ROAD_INSPECTOR\020\322\001\022\023\n\016BRIDGE_OPENING\020\323" +
      "\001\022\031\n\024GHOST_DRIVER_WARNING\020\324\001\022\r\n\010PRIORITY" +
      "\020\255\002\022\025\n\020SELECTIVE_ACCESS\020\256\002\022\031\n\024TRAFFIC_LI" +
      "GHT_STATUS\020\221\003\022\031\n\024TRAFFIC_LIGHT_TIMING\020\222\003" +
      "\022\023\n\016ADVISORY_SPEED\020\223\003\022\031\n\024RAIL_CROSSING_S" +
      "TATUS\020\224\003\022\030\n\023TIRE_PRESSURE_GAUGE\020\365\003\022\016\n\tAL" +
      "TIMETER\020\366\003\022\013\n\006WEIGHT\020\367\003\022\027\n\022PARKING_OCCUP" +
      "ATION\020\370\003\022\030\n\023PARKING_RESERVATION\020\371\003B\002P\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_fmsitsinterface_FmsItsMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fmsitsinterface_FmsItsMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_FmsItsMessage_descriptor,
        new java.lang.String[] { "MessageType", "VehicleId", "Container", });
    internal_static_fmsitsinterface_FmsItsContainer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_fmsitsinterface_FmsItsContainer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_FmsItsContainer_descriptor,
        new java.lang.String[] { "TimestampMessage", "InfoContainer", "ContentContainer", "LocationUpdate", "ErrorMessage", });
    internal_static_fmsitsinterface_ErrorMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_fmsitsinterface_ErrorMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_ErrorMessage_descriptor,
        new java.lang.String[] { "ErrorType", "ErrorMessage", "RelatedField", "RelatedMessage", "RelatedRawMessage", });
    internal_static_fmsitsinterface_TimestampMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_fmsitsinterface_TimestampMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_TimestampMessage_descriptor,
        new java.lang.String[] { "RequestTransmission", "RequestReception", "ResponseTransmission", });
    internal_static_fmsitsinterface_MeasurementType_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_fmsitsinterface_MeasurementType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_MeasurementType_descriptor,
        new java.lang.String[] { "Value", "Unit", });
    internal_static_fmsitsinterface_InfoContainer_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_fmsitsinterface_InfoContainer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_InfoContainer_descriptor,
        new java.lang.String[] { "Author", "EventId", "MessageType", "EventVersion", "CreationTime", "DesiredInterval", });
    internal_static_fmsitsinterface_ContentContainer_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_fmsitsinterface_ContentContainer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_ContentContainer_descriptor,
        new java.lang.String[] { "ItsEventCode", "EventInfo", });
    internal_static_fmsitsinterface_EventInfo_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_fmsitsinterface_EventInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_EventInfo_descriptor,
        new java.lang.String[] { "EventText", "Location", "StaticEventMetadata", "DynamicEventMetadata", });
    internal_static_fmsitsinterface_Point_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_fmsitsinterface_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_Point_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_fmsitsinterface_Location_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_fmsitsinterface_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_Location_descriptor,
        new java.lang.String[] { "Coordinates", "CoordinatesType", "Heading", });
    internal_static_fmsitsinterface_StaticEventMetadata_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_fmsitsinterface_StaticEventMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_StaticEventMetadata_descriptor,
        new java.lang.String[] { "WeatherConditions", "RoadConfiguration", "SpeedInfo", "IvriContainer", "LaneInfo", "SensorInfo", "OvertakingInfo", });
    internal_static_fmsitsinterface_RoadConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_fmsitsinterface_RoadConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_RoadConfiguration_descriptor,
        new java.lang.String[] { "RoadConfigStatus", "MaxSpeed", "RoadConfigLocation", "Flashing", "RedBorder", });
    internal_static_fmsitsinterface_OvertakingInfo_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_fmsitsinterface_OvertakingInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_OvertakingInfo_descriptor,
        new java.lang.String[] { "ApplicableFor", "ExceptFor", });
    internal_static_fmsitsinterface_SpeedInfo_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_fmsitsinterface_SpeedInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_SpeedInfo_descriptor,
        new java.lang.String[] { "MaximumSpeedLimit", "OptimalSpeed", "SpeedLimitUnit", });
    internal_static_fmsitsinterface_IvriContainer_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_fmsitsinterface_IvriContainer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_IvriContainer_descriptor,
        new java.lang.String[] { "PriorityContainer", "TrafficLightStateInformation", "TrafficLightTimingInformation", "TrafficLightSpeedAdvice", });
    internal_static_fmsitsinterface_PriorityContainer_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_fmsitsinterface_PriorityContainer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_PriorityContainer_descriptor,
        new java.lang.String[] { "Status", "Maneuver", "LaneId", });
    internal_static_fmsitsinterface_TrafficLightStateInformation_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_fmsitsinterface_TrafficLightStateInformation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_TrafficLightStateInformation_descriptor,
        new java.lang.String[] { "CurrentState", "Arrow", "Movement", });
    internal_static_fmsitsinterface_TrafficLightTimingInformation_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_fmsitsinterface_TrafficLightTimingInformation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_TrafficLightTimingInformation_descriptor,
        new java.lang.String[] { "MinEndTime", "MaxEndTime", "LikelyTime", });
    internal_static_fmsitsinterface_TrafficLightSpeedAdvice_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_fmsitsinterface_TrafficLightSpeedAdvice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_TrafficLightSpeedAdvice_descriptor,
        new java.lang.String[] { "Advice", "AdviceType", });
    internal_static_fmsitsinterface_LaneInfo_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_fmsitsinterface_LaneInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_LaneInfo_descriptor,
        new java.lang.String[] { "MaxLaneId", "LaneId", "Maneuvers", });
    internal_static_fmsitsinterface_Maneuver_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_fmsitsinterface_Maneuver_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_Maneuver_descriptor,
        new java.lang.String[] { "Direction", "AlwaysYield", });
    internal_static_fmsitsinterface_SensorInfo_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_fmsitsinterface_SensorInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_SensorInfo_descriptor,
        new java.lang.String[] { "TirePressure", "VehicleWeight", "VehicleHeight", });
    internal_static_fmsitsinterface_TirePressure_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_fmsitsinterface_TirePressure_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_TirePressure_descriptor,
        new java.lang.String[] { "Status", "AxleCount", "Anomalies", });
    internal_static_fmsitsinterface_Anomalies_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_fmsitsinterface_Anomalies_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_Anomalies_descriptor,
        new java.lang.String[] { "Axle", "Side", "Measurement", });
    internal_static_fmsitsinterface_VehicleWeight_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_fmsitsinterface_VehicleWeight_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_VehicleWeight_descriptor,
        new java.lang.String[] { "AxleCount", "WeightMeasurements", });
    internal_static_fmsitsinterface_WeightMeasurements_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_fmsitsinterface_WeightMeasurements_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_WeightMeasurements_descriptor,
        new java.lang.String[] { "Axle", "Weight", });
    internal_static_fmsitsinterface_DynamicEventMetadata_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_fmsitsinterface_DynamicEventMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_DynamicEventMetadata_descriptor,
        new java.lang.String[] { "EventSpeed", "EventHeading", });
    internal_static_fmsitsinterface_LocationUpdateEvent_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_fmsitsinterface_LocationUpdateEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_LocationUpdateEvent_descriptor,
        new java.lang.String[] { "Id", "CreationDate", "GeoReference", "Speed", "Heading", "Lifecycle", "DeviceDate", "GpsQuality", });
    internal_static_fmsitsinterface_LocationUpdateEvent_GeoReference_descriptor =
      internal_static_fmsitsinterface_LocationUpdateEvent_descriptor.getNestedTypes().get(0);
    internal_static_fmsitsinterface_LocationUpdateEvent_GeoReference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fmsitsinterface_LocationUpdateEvent_GeoReference_descriptor,
        new java.lang.String[] { "Lat", "Lon", "Type", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
