// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FMS_ITS_Interface_Specification.proto

package fmsitsinterface;

public interface LaneInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fmsitsinterface.LaneInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * total number of lanes at event location, its_event_code LANE_CONFIGURATION, TRAFFIC_LIGHT_STATUS
   * </pre>
   *
   * <code>int32 max_lane_id = 1;</code>
   * @return The maxLaneId.
   */
  int getMaxLaneId();

  /**
   * <pre>
   * indicating the lane at which the event occurs (counting from left to right, starting at 1 till max_lane_id), its_event_code LANE_CONFIGURATION, TRAFFIC_LIGHT_STATUS
   * </pre>
   *
   * <code>int32 lane_id = 2;</code>
   * @return The laneId.
   */
  int getLaneId();

  /**
   * <pre>
   * The different maneuvers for which this traffic light gives info, its_event_code LANE_CONFIGURATION, TRAFFIC_LIGHT_STATUS
   * </pre>
   *
   * <code>repeated .fmsitsinterface.Maneuver maneuvers = 3;</code>
   */
  java.util.List<fmsitsinterface.Maneuver> 
      getManeuversList();
  /**
   * <pre>
   * The different maneuvers for which this traffic light gives info, its_event_code LANE_CONFIGURATION, TRAFFIC_LIGHT_STATUS
   * </pre>
   *
   * <code>repeated .fmsitsinterface.Maneuver maneuvers = 3;</code>
   */
  fmsitsinterface.Maneuver getManeuvers(int index);
  /**
   * <pre>
   * The different maneuvers for which this traffic light gives info, its_event_code LANE_CONFIGURATION, TRAFFIC_LIGHT_STATUS
   * </pre>
   *
   * <code>repeated .fmsitsinterface.Maneuver maneuvers = 3;</code>
   */
  int getManeuversCount();
  /**
   * <pre>
   * The different maneuvers for which this traffic light gives info, its_event_code LANE_CONFIGURATION, TRAFFIC_LIGHT_STATUS
   * </pre>
   *
   * <code>repeated .fmsitsinterface.Maneuver maneuvers = 3;</code>
   */
  java.util.List<? extends fmsitsinterface.ManeuverOrBuilder> 
      getManeuversOrBuilderList();
  /**
   * <pre>
   * The different maneuvers for which this traffic light gives info, its_event_code LANE_CONFIGURATION, TRAFFIC_LIGHT_STATUS
   * </pre>
   *
   * <code>repeated .fmsitsinterface.Maneuver maneuvers = 3;</code>
   */
  fmsitsinterface.ManeuverOrBuilder getManeuversOrBuilder(
      int index);
}
