// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FMS_ITS_Interface_Specification.proto

package fmsitsinterface;

public interface LocationUpdateEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fmsitsinterface.LocationUpdateEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Uniquely identifies this locationUpdateEvent.
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * Uniquely identifies this locationUpdateEvent.
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * should contain the timestamp of the GPS fix in UTC
   * </pre>
   *
   * <code>.google.protobuf.Timestamp creation_date = 2;</code>
   * @return Whether the creationDate field is set.
   */
  boolean hasCreationDate();
  /**
   * <pre>
   * should contain the timestamp of the GPS fix in UTC
   * </pre>
   *
   * <code>.google.protobuf.Timestamp creation_date = 2;</code>
   * @return The creationDate.
   */
  com.google.protobuf.Timestamp getCreationDate();
  /**
   * <pre>
   * should contain the timestamp of the GPS fix in UTC
   * </pre>
   *
   * <code>.google.protobuf.Timestamp creation_date = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreationDateOrBuilder();

  /**
   * <code>.fmsitsinterface.LocationUpdateEvent.GeoReference geo_reference = 3;</code>
   * @return Whether the geoReference field is set.
   */
  boolean hasGeoReference();
  /**
   * <code>.fmsitsinterface.LocationUpdateEvent.GeoReference geo_reference = 3;</code>
   * @return The geoReference.
   */
  fmsitsinterface.LocationUpdateEvent.GeoReference getGeoReference();
  /**
   * <code>.fmsitsinterface.LocationUpdateEvent.GeoReference geo_reference = 3;</code>
   */
  fmsitsinterface.LocationUpdateEvent.GeoReferenceOrBuilder getGeoReferenceOrBuilder();

  /**
   * <code>.fmsitsinterface.MeasurementType speed = 4;</code>
   * @return Whether the speed field is set.
   */
  boolean hasSpeed();
  /**
   * <code>.fmsitsinterface.MeasurementType speed = 4;</code>
   * @return The speed.
   */
  fmsitsinterface.MeasurementType getSpeed();
  /**
   * <code>.fmsitsinterface.MeasurementType speed = 4;</code>
   */
  fmsitsinterface.MeasurementTypeOrBuilder getSpeedOrBuilder();

  /**
   * <code>.fmsitsinterface.MeasurementType heading = 5;</code>
   * @return Whether the heading field is set.
   */
  boolean hasHeading();
  /**
   * <code>.fmsitsinterface.MeasurementType heading = 5;</code>
   * @return The heading.
   */
  fmsitsinterface.MeasurementType getHeading();
  /**
   * <code>.fmsitsinterface.MeasurementType heading = 5;</code>
   */
  fmsitsinterface.MeasurementTypeOrBuilder getHeadingOrBuilder();

  /**
   * <pre>
   * when is the action taking place. Only actual updates are allowed
   * </pre>
   *
   * <code>.fmsitsinterface.LocationUpdateEvent.LifeCycle lifecycle = 6;</code>
   * @return The enum numeric value on the wire for lifecycle.
   */
  int getLifecycleValue();
  /**
   * <pre>
   * when is the action taking place. Only actual updates are allowed
   * </pre>
   *
   * <code>.fmsitsinterface.LocationUpdateEvent.LifeCycle lifecycle = 6;</code>
   * @return The lifecycle.
   */
  fmsitsinterface.LocationUpdateEvent.LifeCycle getLifecycle();

  /**
   * <pre>
   * optional timestamp when the position update was received on the FMS device and can be used when the GPS fix seems to be far of the NTP time
   * </pre>
   *
   * <code>.google.protobuf.Timestamp device_date = 7;</code>
   * @return Whether the deviceDate field is set.
   */
  boolean hasDeviceDate();
  /**
   * <pre>
   * optional timestamp when the position update was received on the FMS device and can be used when the GPS fix seems to be far of the NTP time
   * </pre>
   *
   * <code>.google.protobuf.Timestamp device_date = 7;</code>
   * @return The deviceDate.
   */
  com.google.protobuf.Timestamp getDeviceDate();
  /**
   * <pre>
   * optional timestamp when the position update was received on the FMS device and can be used when the GPS fix seems to be far of the NTP time
   * </pre>
   *
   * <code>.google.protobuf.Timestamp device_date = 7;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDeviceDateOrBuilder();

  /**
   * <pre>
   * deviation in meters with 95% probability
   * </pre>
   *
   * <code>float gps_quality = 8;</code>
   * @return The gpsQuality.
   */
  float getGpsQuality();
}
