// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FMS_ITS_Interface_Specification.proto

package fmsitsinterface;

public interface MeasurementTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fmsitsinterface.MeasurementType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 value = 1;</code>
   * @return The value.
   */
  int getValue();

  /**
   * <code>.fmsitsinterface.MeasurementUnit unit = 2;</code>
   * @return The enum numeric value on the wire for unit.
   */
  int getUnitValue();
  /**
   * <code>.fmsitsinterface.MeasurementUnit unit = 2;</code>
   * @return The unit.
   */
  fmsitsinterface.MeasurementUnit getUnit();
}
