// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FMS_ITS_Interface_Specification.proto

package fmsitsinterface;

/**
 * Protobuf type {@code fmsitsinterface.SpeedInfo}
 */
public final class SpeedInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:fmsitsinterface.SpeedInfo)
    SpeedInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SpeedInfo.newBuilder() to construct.
  private SpeedInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SpeedInfo() {
    speedLimitUnit_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SpeedInfo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return fmsitsinterface.FMSITSInterfaceSpecification.internal_static_fmsitsinterface_SpeedInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return fmsitsinterface.FMSITSInterfaceSpecification.internal_static_fmsitsinterface_SpeedInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            fmsitsinterface.SpeedInfo.class, fmsitsinterface.SpeedInfo.Builder.class);
  }

  public static final int MAXIMUM_SPEED_LIMIT_FIELD_NUMBER = 1;
  private int maximumSpeedLimit_ = 0;
  /**
   * <pre>
   * maximum speed limit, its_event_code MAXIMUM_SPEED
   * </pre>
   *
   * <code>int32 maximum_speed_limit = 1;</code>
   * @return The maximumSpeedLimit.
   */
  @java.lang.Override
  public int getMaximumSpeedLimit() {
    return maximumSpeedLimit_;
  }

  public static final int OPTIMAL_SPEED_FIELD_NUMBER = 2;
  private int optimalSpeed_ = 0;
  /**
   * <pre>
   * optimal speed, its_event_code ADVISORY_SPEED_LIMIT
   * </pre>
   *
   * <code>int32 optimal_speed = 2;</code>
   * @return The optimalSpeed.
   */
  @java.lang.Override
  public int getOptimalSpeed() {
    return optimalSpeed_;
  }

  public static final int SPEED_LIMIT_UNIT_FIELD_NUMBER = 3;
  private int speedLimitUnit_ = 0;
  /**
   * <pre>
   * units in which maximumSpeedLimit and optimalSpeed are expressed, , its_event_code MAXIMUM_SPEED or ADVISORY_SPEED_LIMIT
   * </pre>
   *
   * <code>.fmsitsinterface.MeasurementUnit speed_limit_unit = 3;</code>
   * @return The enum numeric value on the wire for speedLimitUnit.
   */
  @java.lang.Override public int getSpeedLimitUnitValue() {
    return speedLimitUnit_;
  }
  /**
   * <pre>
   * units in which maximumSpeedLimit and optimalSpeed are expressed, , its_event_code MAXIMUM_SPEED or ADVISORY_SPEED_LIMIT
   * </pre>
   *
   * <code>.fmsitsinterface.MeasurementUnit speed_limit_unit = 3;</code>
   * @return The speedLimitUnit.
   */
  @java.lang.Override public fmsitsinterface.MeasurementUnit getSpeedLimitUnit() {
    fmsitsinterface.MeasurementUnit result = fmsitsinterface.MeasurementUnit.forNumber(speedLimitUnit_);
    return result == null ? fmsitsinterface.MeasurementUnit.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (maximumSpeedLimit_ != 0) {
      output.writeInt32(1, maximumSpeedLimit_);
    }
    if (optimalSpeed_ != 0) {
      output.writeInt32(2, optimalSpeed_);
    }
    if (speedLimitUnit_ != fmsitsinterface.MeasurementUnit.UNKNOWN.getNumber()) {
      output.writeEnum(3, speedLimitUnit_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (maximumSpeedLimit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, maximumSpeedLimit_);
    }
    if (optimalSpeed_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, optimalSpeed_);
    }
    if (speedLimitUnit_ != fmsitsinterface.MeasurementUnit.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, speedLimitUnit_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof fmsitsinterface.SpeedInfo)) {
      return super.equals(obj);
    }
    fmsitsinterface.SpeedInfo other = (fmsitsinterface.SpeedInfo) obj;

    if (getMaximumSpeedLimit()
        != other.getMaximumSpeedLimit()) return false;
    if (getOptimalSpeed()
        != other.getOptimalSpeed()) return false;
    if (speedLimitUnit_ != other.speedLimitUnit_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MAXIMUM_SPEED_LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getMaximumSpeedLimit();
    hash = (37 * hash) + OPTIMAL_SPEED_FIELD_NUMBER;
    hash = (53 * hash) + getOptimalSpeed();
    hash = (37 * hash) + SPEED_LIMIT_UNIT_FIELD_NUMBER;
    hash = (53 * hash) + speedLimitUnit_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static fmsitsinterface.SpeedInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fmsitsinterface.SpeedInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fmsitsinterface.SpeedInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fmsitsinterface.SpeedInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fmsitsinterface.SpeedInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fmsitsinterface.SpeedInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fmsitsinterface.SpeedInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fmsitsinterface.SpeedInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static fmsitsinterface.SpeedInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static fmsitsinterface.SpeedInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static fmsitsinterface.SpeedInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fmsitsinterface.SpeedInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(fmsitsinterface.SpeedInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fmsitsinterface.SpeedInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fmsitsinterface.SpeedInfo)
      fmsitsinterface.SpeedInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fmsitsinterface.FMSITSInterfaceSpecification.internal_static_fmsitsinterface_SpeedInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fmsitsinterface.FMSITSInterfaceSpecification.internal_static_fmsitsinterface_SpeedInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fmsitsinterface.SpeedInfo.class, fmsitsinterface.SpeedInfo.Builder.class);
    }

    // Construct using fmsitsinterface.SpeedInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      maximumSpeedLimit_ = 0;
      optimalSpeed_ = 0;
      speedLimitUnit_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return fmsitsinterface.FMSITSInterfaceSpecification.internal_static_fmsitsinterface_SpeedInfo_descriptor;
    }

    @java.lang.Override
    public fmsitsinterface.SpeedInfo getDefaultInstanceForType() {
      return fmsitsinterface.SpeedInfo.getDefaultInstance();
    }

    @java.lang.Override
    public fmsitsinterface.SpeedInfo build() {
      fmsitsinterface.SpeedInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public fmsitsinterface.SpeedInfo buildPartial() {
      fmsitsinterface.SpeedInfo result = new fmsitsinterface.SpeedInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(fmsitsinterface.SpeedInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.maximumSpeedLimit_ = maximumSpeedLimit_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.optimalSpeed_ = optimalSpeed_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.speedLimitUnit_ = speedLimitUnit_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof fmsitsinterface.SpeedInfo) {
        return mergeFrom((fmsitsinterface.SpeedInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(fmsitsinterface.SpeedInfo other) {
      if (other == fmsitsinterface.SpeedInfo.getDefaultInstance()) return this;
      if (other.getMaximumSpeedLimit() != 0) {
        setMaximumSpeedLimit(other.getMaximumSpeedLimit());
      }
      if (other.getOptimalSpeed() != 0) {
        setOptimalSpeed(other.getOptimalSpeed());
      }
      if (other.speedLimitUnit_ != 0) {
        setSpeedLimitUnitValue(other.getSpeedLimitUnitValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              maximumSpeedLimit_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              optimalSpeed_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              speedLimitUnit_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int maximumSpeedLimit_ ;
    /**
     * <pre>
     * maximum speed limit, its_event_code MAXIMUM_SPEED
     * </pre>
     *
     * <code>int32 maximum_speed_limit = 1;</code>
     * @return The maximumSpeedLimit.
     */
    @java.lang.Override
    public int getMaximumSpeedLimit() {
      return maximumSpeedLimit_;
    }
    /**
     * <pre>
     * maximum speed limit, its_event_code MAXIMUM_SPEED
     * </pre>
     *
     * <code>int32 maximum_speed_limit = 1;</code>
     * @param value The maximumSpeedLimit to set.
     * @return This builder for chaining.
     */
    public Builder setMaximumSpeedLimit(int value) {

      maximumSpeedLimit_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * maximum speed limit, its_event_code MAXIMUM_SPEED
     * </pre>
     *
     * <code>int32 maximum_speed_limit = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaximumSpeedLimit() {
      bitField0_ = (bitField0_ & ~0x00000001);
      maximumSpeedLimit_ = 0;
      onChanged();
      return this;
    }

    private int optimalSpeed_ ;
    /**
     * <pre>
     * optimal speed, its_event_code ADVISORY_SPEED_LIMIT
     * </pre>
     *
     * <code>int32 optimal_speed = 2;</code>
     * @return The optimalSpeed.
     */
    @java.lang.Override
    public int getOptimalSpeed() {
      return optimalSpeed_;
    }
    /**
     * <pre>
     * optimal speed, its_event_code ADVISORY_SPEED_LIMIT
     * </pre>
     *
     * <code>int32 optimal_speed = 2;</code>
     * @param value The optimalSpeed to set.
     * @return This builder for chaining.
     */
    public Builder setOptimalSpeed(int value) {

      optimalSpeed_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optimal speed, its_event_code ADVISORY_SPEED_LIMIT
     * </pre>
     *
     * <code>int32 optimal_speed = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOptimalSpeed() {
      bitField0_ = (bitField0_ & ~0x00000002);
      optimalSpeed_ = 0;
      onChanged();
      return this;
    }

    private int speedLimitUnit_ = 0;
    /**
     * <pre>
     * units in which maximumSpeedLimit and optimalSpeed are expressed, , its_event_code MAXIMUM_SPEED or ADVISORY_SPEED_LIMIT
     * </pre>
     *
     * <code>.fmsitsinterface.MeasurementUnit speed_limit_unit = 3;</code>
     * @return The enum numeric value on the wire for speedLimitUnit.
     */
    @java.lang.Override public int getSpeedLimitUnitValue() {
      return speedLimitUnit_;
    }
    /**
     * <pre>
     * units in which maximumSpeedLimit and optimalSpeed are expressed, , its_event_code MAXIMUM_SPEED or ADVISORY_SPEED_LIMIT
     * </pre>
     *
     * <code>.fmsitsinterface.MeasurementUnit speed_limit_unit = 3;</code>
     * @param value The enum numeric value on the wire for speedLimitUnit to set.
     * @return This builder for chaining.
     */
    public Builder setSpeedLimitUnitValue(int value) {
      speedLimitUnit_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * units in which maximumSpeedLimit and optimalSpeed are expressed, , its_event_code MAXIMUM_SPEED or ADVISORY_SPEED_LIMIT
     * </pre>
     *
     * <code>.fmsitsinterface.MeasurementUnit speed_limit_unit = 3;</code>
     * @return The speedLimitUnit.
     */
    @java.lang.Override
    public fmsitsinterface.MeasurementUnit getSpeedLimitUnit() {
      fmsitsinterface.MeasurementUnit result = fmsitsinterface.MeasurementUnit.forNumber(speedLimitUnit_);
      return result == null ? fmsitsinterface.MeasurementUnit.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * units in which maximumSpeedLimit and optimalSpeed are expressed, , its_event_code MAXIMUM_SPEED or ADVISORY_SPEED_LIMIT
     * </pre>
     *
     * <code>.fmsitsinterface.MeasurementUnit speed_limit_unit = 3;</code>
     * @param value The speedLimitUnit to set.
     * @return This builder for chaining.
     */
    public Builder setSpeedLimitUnit(fmsitsinterface.MeasurementUnit value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      speedLimitUnit_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * units in which maximumSpeedLimit and optimalSpeed are expressed, , its_event_code MAXIMUM_SPEED or ADVISORY_SPEED_LIMIT
     * </pre>
     *
     * <code>.fmsitsinterface.MeasurementUnit speed_limit_unit = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpeedLimitUnit() {
      bitField0_ = (bitField0_ & ~0x00000004);
      speedLimitUnit_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:fmsitsinterface.SpeedInfo)
  }

  // @@protoc_insertion_point(class_scope:fmsitsinterface.SpeedInfo)
  private static final fmsitsinterface.SpeedInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new fmsitsinterface.SpeedInfo();
  }

  public static fmsitsinterface.SpeedInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SpeedInfo>
      PARSER = new com.google.protobuf.AbstractParser<SpeedInfo>() {
    @java.lang.Override
    public SpeedInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SpeedInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SpeedInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public fmsitsinterface.SpeedInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

