// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FMS_ITS_Interface_Specification.proto

package fmsitsinterface;

public interface TirePressureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fmsitsinterface.TirePressure)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * indicating overall status of tire pressure of the vehicle.
   * </pre>
   *
   * <code>.fmsitsinterface.TirePressure.VehicleTirePressureStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <pre>
   * indicating overall status of tire pressure of the vehicle.
   * </pre>
   *
   * <code>.fmsitsinterface.TirePressure.VehicleTirePressureStatus status = 1;</code>
   * @return The status.
   */
  fmsitsinterface.TirePressure.VehicleTirePressureStatus getStatus();

  /**
   * <pre>
   * integer indicating total number of axles of the vehicle
   * </pre>
   *
   * <code>int32 axle_count = 2;</code>
   * @return The axleCount.
   */
  int getAxleCount();

  /**
   * <pre>
   * object containing detailed information on pressure of every tire that is not OK
   * </pre>
   *
   * <code>repeated .fmsitsinterface.Anomalies anomalies = 3;</code>
   */
  java.util.List<fmsitsinterface.Anomalies> 
      getAnomaliesList();
  /**
   * <pre>
   * object containing detailed information on pressure of every tire that is not OK
   * </pre>
   *
   * <code>repeated .fmsitsinterface.Anomalies anomalies = 3;</code>
   */
  fmsitsinterface.Anomalies getAnomalies(int index);
  /**
   * <pre>
   * object containing detailed information on pressure of every tire that is not OK
   * </pre>
   *
   * <code>repeated .fmsitsinterface.Anomalies anomalies = 3;</code>
   */
  int getAnomaliesCount();
  /**
   * <pre>
   * object containing detailed information on pressure of every tire that is not OK
   * </pre>
   *
   * <code>repeated .fmsitsinterface.Anomalies anomalies = 3;</code>
   */
  java.util.List<? extends fmsitsinterface.AnomaliesOrBuilder> 
      getAnomaliesOrBuilderList();
  /**
   * <pre>
   * object containing detailed information on pressure of every tire that is not OK
   * </pre>
   *
   * <code>repeated .fmsitsinterface.Anomalies anomalies = 3;</code>
   */
  fmsitsinterface.AnomaliesOrBuilder getAnomaliesOrBuilder(
      int index);
}
