// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FMS_ITS_Interface_Specification.proto

package fmsitsinterface;

/**
 * Protobuf type {@code fmsitsinterface.VehicleWeight}
 */
public final class VehicleWeight extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:fmsitsinterface.VehicleWeight)
    VehicleWeightOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VehicleWeight.newBuilder() to construct.
  private VehicleWeight(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VehicleWeight() {
    weightMeasurements_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new VehicleWeight();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return fmsitsinterface.FMSITSInterfaceSpecification.internal_static_fmsitsinterface_VehicleWeight_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return fmsitsinterface.FMSITSInterfaceSpecification.internal_static_fmsitsinterface_VehicleWeight_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            fmsitsinterface.VehicleWeight.class, fmsitsinterface.VehicleWeight.Builder.class);
  }

  public static final int AXLE_COUNT_FIELD_NUMBER = 1;
  private int axleCount_ = 0;
  /**
   * <pre>
   * integer indicating total number of axles of the vehicle
   * </pre>
   *
   * <code>int32 axle_count = 1;</code>
   * @return The axleCount.
   */
  @java.lang.Override
  public int getAxleCount() {
    return axleCount_;
  }

  public static final int WEIGHT_MEASUREMENTS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<fmsitsinterface.WeightMeasurements> weightMeasurements_;
  /**
   * <pre>
   * contains the weight measurements of the vehicle per axle
   * </pre>
   *
   * <code>repeated .fmsitsinterface.WeightMeasurements weight_measurements = 2;</code>
   */
  @java.lang.Override
  public java.util.List<fmsitsinterface.WeightMeasurements> getWeightMeasurementsList() {
    return weightMeasurements_;
  }
  /**
   * <pre>
   * contains the weight measurements of the vehicle per axle
   * </pre>
   *
   * <code>repeated .fmsitsinterface.WeightMeasurements weight_measurements = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends fmsitsinterface.WeightMeasurementsOrBuilder> 
      getWeightMeasurementsOrBuilderList() {
    return weightMeasurements_;
  }
  /**
   * <pre>
   * contains the weight measurements of the vehicle per axle
   * </pre>
   *
   * <code>repeated .fmsitsinterface.WeightMeasurements weight_measurements = 2;</code>
   */
  @java.lang.Override
  public int getWeightMeasurementsCount() {
    return weightMeasurements_.size();
  }
  /**
   * <pre>
   * contains the weight measurements of the vehicle per axle
   * </pre>
   *
   * <code>repeated .fmsitsinterface.WeightMeasurements weight_measurements = 2;</code>
   */
  @java.lang.Override
  public fmsitsinterface.WeightMeasurements getWeightMeasurements(int index) {
    return weightMeasurements_.get(index);
  }
  /**
   * <pre>
   * contains the weight measurements of the vehicle per axle
   * </pre>
   *
   * <code>repeated .fmsitsinterface.WeightMeasurements weight_measurements = 2;</code>
   */
  @java.lang.Override
  public fmsitsinterface.WeightMeasurementsOrBuilder getWeightMeasurementsOrBuilder(
      int index) {
    return weightMeasurements_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (axleCount_ != 0) {
      output.writeInt32(1, axleCount_);
    }
    for (int i = 0; i < weightMeasurements_.size(); i++) {
      output.writeMessage(2, weightMeasurements_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (axleCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, axleCount_);
    }
    for (int i = 0; i < weightMeasurements_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, weightMeasurements_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof fmsitsinterface.VehicleWeight)) {
      return super.equals(obj);
    }
    fmsitsinterface.VehicleWeight other = (fmsitsinterface.VehicleWeight) obj;

    if (getAxleCount()
        != other.getAxleCount()) return false;
    if (!getWeightMeasurementsList()
        .equals(other.getWeightMeasurementsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AXLE_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getAxleCount();
    if (getWeightMeasurementsCount() > 0) {
      hash = (37 * hash) + WEIGHT_MEASUREMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getWeightMeasurementsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static fmsitsinterface.VehicleWeight parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fmsitsinterface.VehicleWeight parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fmsitsinterface.VehicleWeight parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fmsitsinterface.VehicleWeight parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fmsitsinterface.VehicleWeight parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fmsitsinterface.VehicleWeight parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fmsitsinterface.VehicleWeight parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fmsitsinterface.VehicleWeight parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static fmsitsinterface.VehicleWeight parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static fmsitsinterface.VehicleWeight parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static fmsitsinterface.VehicleWeight parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fmsitsinterface.VehicleWeight parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(fmsitsinterface.VehicleWeight prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fmsitsinterface.VehicleWeight}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fmsitsinterface.VehicleWeight)
      fmsitsinterface.VehicleWeightOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fmsitsinterface.FMSITSInterfaceSpecification.internal_static_fmsitsinterface_VehicleWeight_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fmsitsinterface.FMSITSInterfaceSpecification.internal_static_fmsitsinterface_VehicleWeight_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fmsitsinterface.VehicleWeight.class, fmsitsinterface.VehicleWeight.Builder.class);
    }

    // Construct using fmsitsinterface.VehicleWeight.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      axleCount_ = 0;
      if (weightMeasurementsBuilder_ == null) {
        weightMeasurements_ = java.util.Collections.emptyList();
      } else {
        weightMeasurements_ = null;
        weightMeasurementsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return fmsitsinterface.FMSITSInterfaceSpecification.internal_static_fmsitsinterface_VehicleWeight_descriptor;
    }

    @java.lang.Override
    public fmsitsinterface.VehicleWeight getDefaultInstanceForType() {
      return fmsitsinterface.VehicleWeight.getDefaultInstance();
    }

    @java.lang.Override
    public fmsitsinterface.VehicleWeight build() {
      fmsitsinterface.VehicleWeight result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public fmsitsinterface.VehicleWeight buildPartial() {
      fmsitsinterface.VehicleWeight result = new fmsitsinterface.VehicleWeight(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(fmsitsinterface.VehicleWeight result) {
      if (weightMeasurementsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          weightMeasurements_ = java.util.Collections.unmodifiableList(weightMeasurements_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.weightMeasurements_ = weightMeasurements_;
      } else {
        result.weightMeasurements_ = weightMeasurementsBuilder_.build();
      }
    }

    private void buildPartial0(fmsitsinterface.VehicleWeight result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.axleCount_ = axleCount_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof fmsitsinterface.VehicleWeight) {
        return mergeFrom((fmsitsinterface.VehicleWeight)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(fmsitsinterface.VehicleWeight other) {
      if (other == fmsitsinterface.VehicleWeight.getDefaultInstance()) return this;
      if (other.getAxleCount() != 0) {
        setAxleCount(other.getAxleCount());
      }
      if (weightMeasurementsBuilder_ == null) {
        if (!other.weightMeasurements_.isEmpty()) {
          if (weightMeasurements_.isEmpty()) {
            weightMeasurements_ = other.weightMeasurements_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureWeightMeasurementsIsMutable();
            weightMeasurements_.addAll(other.weightMeasurements_);
          }
          onChanged();
        }
      } else {
        if (!other.weightMeasurements_.isEmpty()) {
          if (weightMeasurementsBuilder_.isEmpty()) {
            weightMeasurementsBuilder_.dispose();
            weightMeasurementsBuilder_ = null;
            weightMeasurements_ = other.weightMeasurements_;
            bitField0_ = (bitField0_ & ~0x00000002);
            weightMeasurementsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getWeightMeasurementsFieldBuilder() : null;
          } else {
            weightMeasurementsBuilder_.addAllMessages(other.weightMeasurements_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              axleCount_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              fmsitsinterface.WeightMeasurements m =
                  input.readMessage(
                      fmsitsinterface.WeightMeasurements.parser(),
                      extensionRegistry);
              if (weightMeasurementsBuilder_ == null) {
                ensureWeightMeasurementsIsMutable();
                weightMeasurements_.add(m);
              } else {
                weightMeasurementsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int axleCount_ ;
    /**
     * <pre>
     * integer indicating total number of axles of the vehicle
     * </pre>
     *
     * <code>int32 axle_count = 1;</code>
     * @return The axleCount.
     */
    @java.lang.Override
    public int getAxleCount() {
      return axleCount_;
    }
    /**
     * <pre>
     * integer indicating total number of axles of the vehicle
     * </pre>
     *
     * <code>int32 axle_count = 1;</code>
     * @param value The axleCount to set.
     * @return This builder for chaining.
     */
    public Builder setAxleCount(int value) {

      axleCount_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * integer indicating total number of axles of the vehicle
     * </pre>
     *
     * <code>int32 axle_count = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAxleCount() {
      bitField0_ = (bitField0_ & ~0x00000001);
      axleCount_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<fmsitsinterface.WeightMeasurements> weightMeasurements_ =
      java.util.Collections.emptyList();
    private void ensureWeightMeasurementsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        weightMeasurements_ = new java.util.ArrayList<fmsitsinterface.WeightMeasurements>(weightMeasurements_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        fmsitsinterface.WeightMeasurements, fmsitsinterface.WeightMeasurements.Builder, fmsitsinterface.WeightMeasurementsOrBuilder> weightMeasurementsBuilder_;

    /**
     * <pre>
     * contains the weight measurements of the vehicle per axle
     * </pre>
     *
     * <code>repeated .fmsitsinterface.WeightMeasurements weight_measurements = 2;</code>
     */
    public java.util.List<fmsitsinterface.WeightMeasurements> getWeightMeasurementsList() {
      if (weightMeasurementsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(weightMeasurements_);
      } else {
        return weightMeasurementsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * contains the weight measurements of the vehicle per axle
     * </pre>
     *
     * <code>repeated .fmsitsinterface.WeightMeasurements weight_measurements = 2;</code>
     */
    public int getWeightMeasurementsCount() {
      if (weightMeasurementsBuilder_ == null) {
        return weightMeasurements_.size();
      } else {
        return weightMeasurementsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * contains the weight measurements of the vehicle per axle
     * </pre>
     *
     * <code>repeated .fmsitsinterface.WeightMeasurements weight_measurements = 2;</code>
     */
    public fmsitsinterface.WeightMeasurements getWeightMeasurements(int index) {
      if (weightMeasurementsBuilder_ == null) {
        return weightMeasurements_.get(index);
      } else {
        return weightMeasurementsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * contains the weight measurements of the vehicle per axle
     * </pre>
     *
     * <code>repeated .fmsitsinterface.WeightMeasurements weight_measurements = 2;</code>
     */
    public Builder setWeightMeasurements(
        int index, fmsitsinterface.WeightMeasurements value) {
      if (weightMeasurementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWeightMeasurementsIsMutable();
        weightMeasurements_.set(index, value);
        onChanged();
      } else {
        weightMeasurementsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * contains the weight measurements of the vehicle per axle
     * </pre>
     *
     * <code>repeated .fmsitsinterface.WeightMeasurements weight_measurements = 2;</code>
     */
    public Builder setWeightMeasurements(
        int index, fmsitsinterface.WeightMeasurements.Builder builderForValue) {
      if (weightMeasurementsBuilder_ == null) {
        ensureWeightMeasurementsIsMutable();
        weightMeasurements_.set(index, builderForValue.build());
        onChanged();
      } else {
        weightMeasurementsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * contains the weight measurements of the vehicle per axle
     * </pre>
     *
     * <code>repeated .fmsitsinterface.WeightMeasurements weight_measurements = 2;</code>
     */
    public Builder addWeightMeasurements(fmsitsinterface.WeightMeasurements value) {
      if (weightMeasurementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWeightMeasurementsIsMutable();
        weightMeasurements_.add(value);
        onChanged();
      } else {
        weightMeasurementsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * contains the weight measurements of the vehicle per axle
     * </pre>
     *
     * <code>repeated .fmsitsinterface.WeightMeasurements weight_measurements = 2;</code>
     */
    public Builder addWeightMeasurements(
        int index, fmsitsinterface.WeightMeasurements value) {
      if (weightMeasurementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWeightMeasurementsIsMutable();
        weightMeasurements_.add(index, value);
        onChanged();
      } else {
        weightMeasurementsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * contains the weight measurements of the vehicle per axle
     * </pre>
     *
     * <code>repeated .fmsitsinterface.WeightMeasurements weight_measurements = 2;</code>
     */
    public Builder addWeightMeasurements(
        fmsitsinterface.WeightMeasurements.Builder builderForValue) {
      if (weightMeasurementsBuilder_ == null) {
        ensureWeightMeasurementsIsMutable();
        weightMeasurements_.add(builderForValue.build());
        onChanged();
      } else {
        weightMeasurementsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * contains the weight measurements of the vehicle per axle
     * </pre>
     *
     * <code>repeated .fmsitsinterface.WeightMeasurements weight_measurements = 2;</code>
     */
    public Builder addWeightMeasurements(
        int index, fmsitsinterface.WeightMeasurements.Builder builderForValue) {
      if (weightMeasurementsBuilder_ == null) {
        ensureWeightMeasurementsIsMutable();
        weightMeasurements_.add(index, builderForValue.build());
        onChanged();
      } else {
        weightMeasurementsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * contains the weight measurements of the vehicle per axle
     * </pre>
     *
     * <code>repeated .fmsitsinterface.WeightMeasurements weight_measurements = 2;</code>
     */
    public Builder addAllWeightMeasurements(
        java.lang.Iterable<? extends fmsitsinterface.WeightMeasurements> values) {
      if (weightMeasurementsBuilder_ == null) {
        ensureWeightMeasurementsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, weightMeasurements_);
        onChanged();
      } else {
        weightMeasurementsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * contains the weight measurements of the vehicle per axle
     * </pre>
     *
     * <code>repeated .fmsitsinterface.WeightMeasurements weight_measurements = 2;</code>
     */
    public Builder clearWeightMeasurements() {
      if (weightMeasurementsBuilder_ == null) {
        weightMeasurements_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        weightMeasurementsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * contains the weight measurements of the vehicle per axle
     * </pre>
     *
     * <code>repeated .fmsitsinterface.WeightMeasurements weight_measurements = 2;</code>
     */
    public Builder removeWeightMeasurements(int index) {
      if (weightMeasurementsBuilder_ == null) {
        ensureWeightMeasurementsIsMutable();
        weightMeasurements_.remove(index);
        onChanged();
      } else {
        weightMeasurementsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * contains the weight measurements of the vehicle per axle
     * </pre>
     *
     * <code>repeated .fmsitsinterface.WeightMeasurements weight_measurements = 2;</code>
     */
    public fmsitsinterface.WeightMeasurements.Builder getWeightMeasurementsBuilder(
        int index) {
      return getWeightMeasurementsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * contains the weight measurements of the vehicle per axle
     * </pre>
     *
     * <code>repeated .fmsitsinterface.WeightMeasurements weight_measurements = 2;</code>
     */
    public fmsitsinterface.WeightMeasurementsOrBuilder getWeightMeasurementsOrBuilder(
        int index) {
      if (weightMeasurementsBuilder_ == null) {
        return weightMeasurements_.get(index);  } else {
        return weightMeasurementsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * contains the weight measurements of the vehicle per axle
     * </pre>
     *
     * <code>repeated .fmsitsinterface.WeightMeasurements weight_measurements = 2;</code>
     */
    public java.util.List<? extends fmsitsinterface.WeightMeasurementsOrBuilder> 
         getWeightMeasurementsOrBuilderList() {
      if (weightMeasurementsBuilder_ != null) {
        return weightMeasurementsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(weightMeasurements_);
      }
    }
    /**
     * <pre>
     * contains the weight measurements of the vehicle per axle
     * </pre>
     *
     * <code>repeated .fmsitsinterface.WeightMeasurements weight_measurements = 2;</code>
     */
    public fmsitsinterface.WeightMeasurements.Builder addWeightMeasurementsBuilder() {
      return getWeightMeasurementsFieldBuilder().addBuilder(
          fmsitsinterface.WeightMeasurements.getDefaultInstance());
    }
    /**
     * <pre>
     * contains the weight measurements of the vehicle per axle
     * </pre>
     *
     * <code>repeated .fmsitsinterface.WeightMeasurements weight_measurements = 2;</code>
     */
    public fmsitsinterface.WeightMeasurements.Builder addWeightMeasurementsBuilder(
        int index) {
      return getWeightMeasurementsFieldBuilder().addBuilder(
          index, fmsitsinterface.WeightMeasurements.getDefaultInstance());
    }
    /**
     * <pre>
     * contains the weight measurements of the vehicle per axle
     * </pre>
     *
     * <code>repeated .fmsitsinterface.WeightMeasurements weight_measurements = 2;</code>
     */
    public java.util.List<fmsitsinterface.WeightMeasurements.Builder> 
         getWeightMeasurementsBuilderList() {
      return getWeightMeasurementsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        fmsitsinterface.WeightMeasurements, fmsitsinterface.WeightMeasurements.Builder, fmsitsinterface.WeightMeasurementsOrBuilder> 
        getWeightMeasurementsFieldBuilder() {
      if (weightMeasurementsBuilder_ == null) {
        weightMeasurementsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            fmsitsinterface.WeightMeasurements, fmsitsinterface.WeightMeasurements.Builder, fmsitsinterface.WeightMeasurementsOrBuilder>(
                weightMeasurements_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        weightMeasurements_ = null;
      }
      return weightMeasurementsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:fmsitsinterface.VehicleWeight)
  }

  // @@protoc_insertion_point(class_scope:fmsitsinterface.VehicleWeight)
  private static final fmsitsinterface.VehicleWeight DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new fmsitsinterface.VehicleWeight();
  }

  public static fmsitsinterface.VehicleWeight getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VehicleWeight>
      PARSER = new com.google.protobuf.AbstractParser<VehicleWeight>() {
    @java.lang.Override
    public VehicleWeight parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VehicleWeight> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VehicleWeight> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public fmsitsinterface.VehicleWeight getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

