// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FMS_ITS_Interface_Specification.proto

package fmsitsinterface;

public interface WeightMeasurementsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fmsitsinterface.WeightMeasurements)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * indicating axle, counting starts from top of vehicle
   * </pre>
   *
   * <code>int32 axle = 1;</code>
   * @return The axle.
   */
  int getAxle();

  /**
   * <code>.fmsitsinterface.MeasurementType weight = 2;</code>
   * @return Whether the weight field is set.
   */
  boolean hasWeight();
  /**
   * <code>.fmsitsinterface.MeasurementType weight = 2;</code>
   * @return The weight.
   */
  fmsitsinterface.MeasurementType getWeight();
  /**
   * <code>.fmsitsinterface.MeasurementType weight = 2;</code>
   */
  fmsitsinterface.MeasurementTypeOrBuilder getWeightOrBuilder();
}
